import { nanoid } from 'nanoid'
const labels:Record<string,string>={titlePromise:'系列承诺',logline:'一句话梗概',coreTheme:'核心主题',emotionalPromise:'情感体验',audiencePromise:'观众期待',storyEngine:'叙事动力',worldRules:'故事规则',seasonArc:'整季发展',protagonistArc:'主角弧线',relationshipArcs:'关系发展',episodeArchitecture:'单集结构',hookPatterns:'钩子类型',visualLanguage:'视觉语言',soundLanguage:'声音语言',continuityRules:'连续性规则',productionConstraints:'制作约束',label:'名称',kind:'类型',identity:'身份定义',appearance:'外观',palette:'配色',materials:'材质',continuityLocks:'一致性锚点',prohibitedChanges:'禁止变化',basePrompt:'素材提示词',negativePrompt:'负向约束',referenceBrief:'参考需求',sourceUnitKeys:'来源片段',stableKey:'稳定编号',episodeNumber:'所属集数',title:'标题',synopsis:'内容概述',openingHook:'开场钩子',beats:'节拍',endHook:'结尾钩子',continuityIn:'承接状态',continuityOut:'结束状态',order:'排列顺序',function:'节拍作用',visibleAction:'可见动作',conflict:'冲突',turn:'转折',targetSeconds:'目标秒数',sceneNumber:'场次',heading:'场景标题',location:'地点',timeOfDay:'时间',dramaticPurpose:'叙事目的',entryState:'进入状态',exitState:'退出状态',dialogue:'对白',narration:'旁白',soundCues:'声音提示',emotionalTurn:'情感变化',estimatedSeconds:'预计秒数',characterKeys:'角色编号',speakerKey:'说话角色编号',text:'内容',delivery:'表演方式',cue:'声音描述',timing:'时间点',subjectKey:'物料编号',sceneKey:'所属场景编号',shotKey:'镜头编号',shotNumber:'镜号',narrativeFunction:'镜头职责',shotSize:'景别',cameraAngle:'机位',cameraMovement:'镜头运动',composition:'构图',performance:'表演',lighting:'光线',transitionIn:'进入转场',transitionOut:'退出转场',soundPlan:'声音计划',subjectKeys:'引用物料编号',imagePrompt:'画面提示词',negativeImagePrompt:'画面负向约束',firstFramePrompt:'起始帧提示词',keyFramePrompt:'关键帧提示词',lastFramePrompt:'结束帧提示词',videoPrompt:'运动提示词',negativeVideoPrompt:'运动负向约束',version:'协议版本',expectedRevision:'依据版本'}
const choices:Record<string,string[]>={function:['hook','setup','pressure','reveal','reversal','climax','cliffhanger','resolution'],shotSize:['extreme-wide','wide','full','medium','close-up','extreme-close-up','insert'],cameraAngle:['eye-level','high','low','overhead','dutch','pov'],cameraMovement:['static','pan','tilt','dolly','track','handheld','zoom','orbit'],kind:['character','costume','location','prop','style','voice','sound','ambience','sfx','music']}
const templates:Record<string,unknown>={dialogue:{speakerKey:'',text:'',delivery:'',estimatedSeconds:3},soundCues:{kind:'sfx',cue:'',timing:'',subjectKey:null},soundPlan:{kind:'sfx',cue:'',timing:'',subjectKey:null}}
export default function MotionFields({value,onChange,name='',path='内容',removalLabel}:{value:unknown;onChange:(v:unknown)=>void;name?:string;path?:string;removalLabel?:string}){
 const label=labels[name]??name
 if(Array.isArray(value))return <fieldset className="mm-field-list"><legend>{label||'内容条目'}</legend>{value.map((item,i)=><div className="mm-field-item" key={i}><MotionFields value={item} name={name} path={`${path} ${i+1}`} onChange={v=>onChange(value.map((old,j)=>j===i?v:old))}/><button type="button" onClick={()=>onChange(value.filter((_,j)=>j!==i))}>{removalLabel??`移除第 ${i+1} 项`}</button>{i>0&&<button type="button" onClick={()=>{const copy=[...value];[copy[i-1],copy[i]]=[copy[i],copy[i-1]];onChange(copy)}}>上移</button>}</div>)}<button type="button" onClick={()=>{let item=structuredClone(templates[name]??value[0]??'');if(item&&typeof item==='object'&&!Array.isArray(item)&&'stableKey' in item){item={...item,stableKey:`${String(item.stableKey)}.${nanoid(6)}`,order:value.length,...('shotNumber' in item?{shotNumber:value.length+1}:{}),...('sceneNumber' in item?{sceneNumber:value.length+1}:{})}}onChange([...value,item])}}>添加{label||'条目'}</button></fieldset>
 if(value!==null&&typeof value==='object')return <div className="mm-fields">{Object.entries(value).map(([key,item])=><MotionFields key={key} value={item} name={key} path={`${path} · ${labels[key]??key}`} onChange={v=>onChange({...value,[key]:v})}/>)}</div>
 if(name==='version'||name==='expectedRevision')return <small>{label} · {String(value)}</small>
 if(choices[name])return <label>{label}<select aria-label={path} value={String(value??'')} onChange={e=>onChange(e.target.value)}>{choices[name].map(c=><option key={c}>{c}</option>)}</select></label>
 if(typeof value==='number')return <label>{label}<input aria-label={path} type="number" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>
 return <label>{label}<textarea aria-label={path} rows={name.includes('Key')||name==='stableKey'?1:3} value={String(value??'')} onChange={e=>onChange(value===null&&!e.target.value?null:e.target.value)}/></label>
}
