import{allPages,products}from'./catalog';
import type{Product,Page}from'./catalog';
import{Icon,Btn,Tag,Fields,Field,CheckList,Row,Progress,Book,asset,Table,Tabs}from'./ui';
type Props={type:string;product:Product;page:Page;close:()=>void;navigate:(s:string)=>void;query:string;setQuery:(s:string)=>void;hasWorld:boolean};
const titles:Record<string,string>={create:'开始一份新的作品','create-world':'创建世界', 'world-required':'开始制作，需要一个世界引擎',candidate:'对照并确认候选',generate:'准备本次生成',export:'导出与交付',import:'导入内容',upload:'选择与预览文件',delete:'删除前，确认影响范围',restore:'恢复这个版本',branch:'从这里，开始新的分支',save:'保存当前进度',saved:'修改已保存',failure:'这一步需要处理',start:'确认开始制作',states:'弹窗与状态样式',references:'本轮设计依据',index:'全部页面', 'version-compare':'版本差异', 'outlet-edit':'调整世界数据出口', 'source-details':'来源与读取依据', 'defeat':'这次旅程，暂时停在这里', 'inventory':'背包', 'shop':'潮汐杂货铺', 'craft':'制作台', 'reading-settings':'阅读与演出设置', 'connection':'连接检查', 'import-progress':'导入进度', 'intent':'确认这次行动意图', 'safety':'暂停与信息边界'};
export function Modal(p:Props){const {type:t,product}=p;const title=titles[t]||({character:'人物档案',scene:'添加场景',chapter:'添加章节',shot:'编辑镜头',seat:'席位设置',travel:'准备前往',item:'物品详情',equipment:'装备与比较',quest:'任务详情',media:'素材详情',prompt:'提示词模板',settings:'配置设置',sync:'本地文件差异',routing:'任务模型路由',gm:'主持工具',tabletop:'地图与桌面',journal:'任务与见闻','scene-switch':'场景推进',offline:'离线生活',daily:'小镇日报'} as Record<string,string>)[t]||'查看与调整';return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)p.close()}}><section role="dialog" aria-modal="true" aria-label={title} className={`modal ${['index','references','states','candidate','version-compare','tabletop'].includes(t)?'wide-modal':''}`}><header className="modal-header"><div><span className="eyebrow">{product.name} · {t==='index'?'PAGE ATLAS':'STORYFORGE'}</span><h2>{title}</h2></div><button className="round-btn" aria-label="关闭" onClick={p.close}><Icon name="X"/></button></header><div className="modal-content">{content(p)}</div>{!['index','states','references'].includes(t)&&<footer className="modal-footer"><small>样式预览 · 示例内容</small><button className="btn" onClick={p.close}>返回</button>{!['saved','failure','defeat','world-required'].includes(t)&&<button className="btn primary" onClick={p.close}>确认{t==='delete'?'删除':t==='export'?'导出':t==='restore'?'恢复':''}<Icon name="Check" size={16}/></button>}</footer>}</section></div>}
function content(p:Props){const {type:t,product}=p;
if(t==='index')return <><div className="big-search compact"><Icon name="Search"/><input placeholder="搜索产品或页面…" value={p.query} onChange={e=>p.setQuery(e.target.value)}/><Tag>{allPages.length} 个页面</Tag></div><div className="atlas">{products.map(x=><section key={x.id}><h3>{x.name}<small>{x.pages.length}</small></h3><div>{x.pages.filter(y=>(x.name+y.label).includes(p.query)).map(y=><button key={y.id} onClick={()=>{p.navigate(`${x.id}/${y.id}`);p.close()}}><span>{y.label}</span><small>{y.group}</small><Icon name="ArrowRight" size={14}/></button>)}</div></section>)}</div></>;
if(t==='states')return <div className="state-atlas">{[['create','新建作品'],['world-required','尚未选择世界'],['candidate','候选与差异'],['generate','生成配置'],['failure','失败与恢复'],['version-compare','版本过期与对比'],['release','发布前确认'],['export','导出与格式'],['import-progress','导入中'],['sync','文件冲突'],['delete','删除影响'],['restore','恢复版本'],['branch','创建分支'],['save','保存进度'],['defeat','战败恢复'],['reading-settings','阅读设置'],['outlet-edit','世界出口修改'],['shop','商店交易'],['craft','配方制作'],['safety','共识与暂停']].map(([id,label])=><button data-modal={id} key={id}><Icon name="Layers" size={24}/><strong>{label}</strong><small>查看样式</small><Icon name="ArrowRight" size={16}/></button>)}</div>;
if(t==='world-required')return <><div className="require-world-art"><Icon name="Globe2" size={58}/></div><h3 className="center">你的方案已经保留。</h3><p className="center">选择一个世界版本，为这次制作提供人物、地点和规则。<br/>选择之后，可以回到这里继续。</p><div className="world-modal-choice"><img src={asset('mist-bg-harbor.webp')}/><div><strong>雾海群岛</strong><p>已封存 · v1.3 · 12 个地点</p></div><button className="btn primary" onClick={()=>{p.navigate(`${product.id}/source`);p.close()}}>选择世界 <Icon name="ArrowRight" size={15}/></button></div><div className="rule"/><div className="row-between"><span>不使用世界引擎尝试制作</span><Tag tone="neutral">后续设计</Tag></div></>;
if(t==='candidate'||t==='version-compare'||t==='sync')return <><div className="row-between"><Tag tone="warm">有 2 处变化需要确认</Tag><small>第三章 · 海水退去以后</small></div><div className="diff-columns modal-diff"><div><h4>{t==='sync'?'项目中的内容':'当前版本'}</h4><p>林舟推开门。门上的铜铃没有响。他走向柜台，看着女人手中的信。</p><p>“我来取一封信。”他说。</p></div><div><h4>{t==='sync'?'本地文件内容':'修改候选'}</h4><p>林舟推开门。<ins>他记得铃声曾经清脆得像阳光。</ins>如今门上的铜铃没有响，<ins>只有潮湿的风跟着他进来。</ins></p><p>“我来取一封信。”他说。</p></div></div><Field label="本次修改说明" value="补充铜铃的前后反差，保留原场景动作与对白。" type="area"/><CheckList items={['正文这一段','关联伏笔记录','检查后续大纲影响']}/></>;
if(t==='create'||t==='create-world')return <><p className="muted">{product.upper?'先写下方向，世界来源可以稍后在本产品中选择。':'留下一个名字，让故事从这里开始。'}</p><Fields fields={['名称|'+(t==='create-world'?'我的新世界':product.book),'一句话介绍|'+product.tagline+'|area',...(product.id==='script'||product.id==='comic'||product.id==='motion'?['原作来源|本地小说 / 粘贴 / 上传|select']:[]),...(product.upper?['体验方向|人物、探索与故事|select']:['目标篇幅|稍后设置|select']),'本地文件夹|可选，稍后绑定|select']}/><div className="callout"><Icon name="Feather"/><p>创建草稿后，可以继续完善方向；本次不会自动开始 AI 制作。</p></div></>;
if(t==='export')return <><div className="world-modal-choice"><Book small title={product.book} image={product.image}/><div><h3>{product.book}</h3><Tag>v1.3 · 内容已固定</Tag><p>选择想要带走的内容。</p></div></div><Fields fields={['导出范围|当前版本的完整内容|select','导出格式|'+(product.id==='script'?'Fountain':product.id==='comic'?'CBZ':product.id==='motion'?'提示词与参考素材包':product.upper?'作品发布包':'Markdown')+'|select','文件名|'+product.book+'-v1.3']}/><CheckList items={['包含内容目录','包含来源与署名','包含素材（格式支持时）']}/></>;
if(t==='generate'||t==='start')return <><Fields fields={['本次目标|'+p.page.label,'生成范围|当前选中内容|select','额外要求|保持人物目标、风格和已确认内容的一致性。|area','模型配置|继承当前产品设置|select']}/><CheckList items={['只修改选中范围','结果先作为候选，等待我确认','保留已经确认的其他内容']}/><div className="callout"><Icon name="Clock"/><p>开始后，进度和每一步产出会出现在制作流程中。</p></div></>;
if(t==='failure')return <><div className="callout warm"><Icon name="AlertCircle" size={27}/><div><strong>场景规则制作暂时中断</strong><p>有一处地点引用尚未纳入本次来源范围。</p></div></div><Row title="已经完成" detail="结构计划、4 份角色快照、8 张场景卡" icon="Check"/><Row title="需要处理" detail="补齐“沉钟湾”的地点来源" icon="Globe2"/><Row title="继续位置" detail="第 3 步 · 规则与交互" icon="GitBranch"/><div className="inline-actions"><Btn primary modal="outlet-edit">修正来源</Btn><Btn modal="start">从这一步继续</Btn><Btn modal="task-details">查看运行记录</Btn></div></>;
if(t==='outlet-edit'||t==='source-details')return <><Tag>雾海群岛 · v1.3</Tag><Fields fields={['出口名称|'+product.name+' · 世界来源','纳入人物|顾晚汐、林舟、余澜|area','纳入地点|旧邮局、北岸码头、灯塔|area','世界规则|潮汐记忆、听潮者与自然边界|area','修改说明|本产品只保留与当前体验直接相关的内容。|area']}/><CheckList items={['保留世界版本与来源说明','历史资料按需读取','其他作品的私密运行记录不纳入']}/></>;
if(t==='delete')return <><div className="callout warm"><Icon name="AlertCircle"/><div><strong>删除「{product.book}」中的当前对象</strong><p>请确认你要删除的是作品、版本还是一份存档。</p></div></div><Field label="删除对象" value="当前选中的存档" type="select"/><CheckList items={['已查看关联内容与影响范围','保留原作品与其他存档','删除前导出备份']}/><p>这一操作的确认样式与普通保存分开，避免误删整份作品。</p></>;
if(t==='save'||t==='branch'||t==='restore')return <><Fields fields={['名称|'+(t==='branch'?'邮局里的另一种选择':'旧邮局的午后'),'说明|'+(t==='restore'?'从这个版本恢复到新的草稿，保留当前版本。':'保留此刻的内容与状态，稍后继续。')+'|area','使用版本|'+product.book+' · v1.0|select']}/><CheckList items={['保留当前时间线','包括角色、任务和关系状态']}/></>;
if(t==='defeat')return <><div className="defeat-symbol"><Icon name="Swords" size={56}/></div><p className="center">这次战斗失败了。你可以选择如何继续。<br/>失败的记录会被保留，故事仍有新的路径。</p><div className="recovery-choices"><button data-modal="branch"><Icon name="GitBranch" size={26}/><h3>战前重试</h3><p>从战斗前的检查点建立新分支。</p></button><button data-modal="restore"><Icon name="Heart" size={26}/><h3>复活点恢复</h3><p>保留已发生的进度与消耗。</p></button></div></>;
if(t==='reading-settings')return <><Field label="文字速度" value="适中" type="select"/><label className="range-field">文字大小<input type="range" defaultValue="55"/></label>{['背景与角色图像','环境声与音乐','自动播放','仅快进已读内容','减少动画效果'].map(x=><label className="toggle-row" key={x}><span>{x}</span><input type="checkbox" defaultChecked={x!=='自动播放'}/></label>)}<label className="range-field">声音音量<input type="range" defaultValue="65"/></label></>;
if(t==='shop'||t==='craft')return <><div className="row-between"><h3>{t==='shop'?'潮汐杂货铺':'已经掌握的配方'}</h3><Tag>持有 128 港币</Tag></div><Table heads={[t==='shop'?'物品':'配方','用途',t==='shop'?'价格':'材料','']} rows={['恢复药剂','航海干粮','旧铜短剑'].map((x,i)=>[<strong>{x}</strong>,['恢复 30 生命','恢复体力','攻击 +8'][i],t==='shop'?`${[20,8,80][i]} 港币`:'潮生草 ×2 / 盐水 ×1',<Btn small modal="action">{t==='shop'?'购买':'制作'}</Btn>])}/><Fields fields={['数量|1','选中物品|恢复药剂|select']}/><p>先查看消耗与结果，再确认这次交易或制作。</p></>;
if(t==='import-progress')return <><div className="row-between"><h3>正在整理你的文档</h3><Tag>第 8 / 12 块</Tag></div><Progress value={66}/><p>已经完成的内容会保留，可以暂停后继续。</p><Row title="正文结构" detail="识别 12 个章节" status="已完成"/><Row title="人物与地点" detail="已提取 8 位人物 / 12 个地点" status="已完成"/><Row title="来源与差异" detail="正在比对已有内容" status="进行中"/><div className="inline-actions"><Btn modal="paused">暂停</Btn><Btn modal="failure">查看失败样式</Btn><Btn modal="candidate">预览已完成结果</Btn></div></>;
if(t==='intent')return <><Field label="你想尝试的行动" value="我想让顾晚汐看看这把钥匙，问问她是否认识它。" type="area"/><Row title="对应行动" detail="询问物件来历 · 目标：顾晚汐" icon="MessageCircle"/><Row title="前置条件" detail="持有旧铜钥匙 · 顾晚汐在场" status="满足"/><Row title="可能消耗" detail="世界时间推进 10 分钟" icon="Clock"/><p>确认后执行系统行动，再展示实际结果。</p></>;
if(t==='saved')return <div className="success-state"><span><Icon name="Check" size={40}/></span><h3>已保存这一刻的想法</h3><p>这是样式预览中的完成反馈。</p></div>;
if(t==='upload')return <><div className="upload-zone"><Icon name="Upload" size={40}/><h3>拖入文件，或从本地选择</h3><p>先预览文件内容与用途，再确认采用。</p><Btn>选择文件</Btn></div><Fields fields={['用途|参考素材|select','来源与署名|作者自有素材','使用范围|当前作品|select']}/></>;
if(t==='safety')return <><Fields fields={['当前状态|已暂停|select','需要避开的内容|过度血腥、未经确认的角色控制。|area','私密信息范围|仅本人和主持人可见|select']}/><CheckList items={['我已知晓本次体验中的 AI 身份','继续前确认所有参与者的边界']}/><Btn primary modal="saved">确认共识并继续</Btn></>;
if(t==='release')return <><div className="callout"><Icon name="Layers"/><div><strong>{product.id==='world'?'封存这一版世界':product.upper?'发布到本产品作品库':'保存一个可回看的版本'}</strong><p>{product.id==='world'?'固定已确认的世界内容，为产品提供可追溯的版本。':'检查本次内容与范围，为这个版本写下说明。'}</p></div></div><Fields fields={['版本名称|灯塔重新亮起之后','版本号|v1.3','版本说明|确认内容、素材和来源，补齐检查中发现的问题。|area']}/><CheckList items={product.id==='world'?['世界规则与内容已确认','来源说明与许可已确认','封存后继续修改将进入新草稿']:['方案与内容已由作者确认','来源与素材使用范围完整','检查与试玩已通过','保留当前草稿与旧版本']}/><Row title="保存位置" detail={product.name+' · '+(product.id==='world'?'封存版本':'作品库')} icon="Library"/></>;
if(t==='community-detail')return <><div className="source-book-row"><Book small title="雾港失踪案" image="mist-market.webp"/><div><Tag>跑团 · v1.3 · 免费</Tag><h2>雾港失踪案</h2><p>作者：悬象 · ★ 4.8 · 24 条评价</p><p>3–4 位玩家 / 约 120 分钟 / 包含角色卡与地图</p></div></div><p className="serif">港口有三位船员失踪。留在旧邮局里的信，写着明天才会发生的事。邀请你的伙伴，沿着退潮后出现的足迹寻找真相。</p><Tabs items={['作品介绍','内容与许可','更新记录','玩家评价']}/><CheckList items={['允许下载到自己的本地作品库','保留来源与创作者署名','运行存档由玩家本人保存']}/><div className="inline-actions"><Btn primary modal="community-owned">领取免费版本</Btn><Btn modal="purchase">查看付费订单样式</Btn><Btn modal="saved">收藏 / 关注更新</Btn><Btn modal="rating">评分评价</Btn></div></>;
if(t==='community-owned')return <><div className="callout"><Icon name="Check"/><div><strong>这个版本已加入拥有列表</strong><p>你可以下载发布包，然后预览导入目标。</p></div></div><Row title="雾港失踪案 v1.3" detail="作者：悬象 · 跑团作品" icon="Package"/><div className="inline-actions"><Btn primary modal="export">下载已拥有版本</Btn><Btn modal="import-progress">预览导入到跑团作品库</Btn></div></>;
if(t==='purchase')return <><Fields fields={['发行作品|灯塔来信 v1.0','价格|¥ 12.00','订单状态|待支付','许可|个人游玩与存档|select']}/><p>完成订单后在已拥有列表下载，再确认导入本地。</p><div className="callout"><Icon name="Info"/><p>样式预览中的示例订单。</p></div></>;
if(t==='derive')return <><div className="row-between"><Tag>{product.book} · 已确认内容</Tag><Icon name="ArrowRight"/><Tag>雾海群岛 · 新草稿</Tag></div><Fields fields={['世界名称|雾海群岛','派生说明|从已确认的正文与设定整理，保留源位置。|area']}/><Table heads={['世界组件','提取内容','状态']} rows={[[<strong>人物</strong>,'顾晚汐、林舟、余澜等 8 位',<Tag>待审阅</Tag>],[<strong>地点</strong>,'旧邮局、北岸码头等 12 处',<Tag>待审阅</Tag>],[<strong>规则与事实</strong>,'6 条规则 · 24 条事实',<Tag>待审阅</Tag>]]}/><CheckList items={['确认保存为独立的世界草稿','保留本次派生的来源版本','原作品继续独立编辑']}/></>;
const specific:Record<string,string[]>={
 settings:['温度|0.8','最大输出|8,192 tokens','上下文窗口|模型默认|select','向量检索|使用当前向量预设|select','主题|青绿纸面|select','正文默认字号|18 px','入门引导|需要时重新查看|select'],
 'media-settings':['图像服务|继承通用连接|select','图像模型|已配置图像模型|select','音频服务|独立音频配置|select','默认画幅|根据具体产品|select','参考图策略|作者确认后采用|select'],
 routing:['产品与任务|长篇 · 正文续写|select','模型预设|长篇精修|select','创作方式|先生成候选|select','本轮预算|¥ 5.00','额外参数|继承预设|select'],
 preset:['预设名称|长篇精修','基于配置|日常创作|select','适用范围|长篇正文与审校|area'],
 'local-model':['本地服务|Ollama / LM Studio|select','服务地址|http://127.0.0.1:11434','模型|从本地服务读取|select'],
 connection:['连接状态|连接成功 · 480 ms','服务|自定义兼容接口','可用模型|3 个文本模型 / 1 个图像模型','诊断|已完成地址、鉴权和模型读取检查。|area'],
 character:['姓名|顾晚汐','角色身份|旧邮局管理员','人物目标|在邮局关闭前处理所有未寄出的信。|area','秘密与边界|父亲的信仅在关系条件满足后公开。|area','关系|林舟：旧友；余澜：邻居|area','参考图|作者已确认的人物参考|select'],
 scene:['场景名称|雨后的旧邮局','地点与人物|旧邮局 · 顾晚汐、林舟','场景目标|确认父亲的信仍然存在。|area','关键线索|信封笔迹、旧铜钥匙、沉默的铜铃|area','进入与离开条件|抵达邮局；获得信件或约定稍后返回。|area'],
 shot:['镜头编号|EP01-SH03','时长|6 秒','景别与运动|近景 · 缓慢推近|select','画面|手指抚过信封上的笔迹，雨水从窗边滴落。|area','声音与对白|轻微雨声 / 无对白|area','来源|第 1 集 · 第 3 场'],
 equipment:['装备|旧铜短剑','部位|主手|select','当前属性|攻击 12 → 20','装备要求|力量 5 / 当前满足','替换物品|练习短剑','变化说明|攻击 +8，重量 +1，替换后的装备放回背包。|area'],
 item:['物品|旧铜钥匙','持有数量|1','用途|开启旧邮局信柜','来源|第二章 · 北岸码头','可用动作|查看 / 使用 / 交付|select'],
 travel:['目的地|北屿灯塔','路线|沿海旧道|select','预计耗时|40 分钟','资源消耗|体力 8 / 港币 0','路况|黄昏前可通行，有低概率遭遇。|area'],
 dice:['检定|交涉','目标|顾晚汐|select','掷骰方式|2d6 + 1','难度与代价|7–9 部分成功，10+ 完全成功；失败推进警觉。|area','可见范围|全桌公开|select'],
 gm:['当前场景|潮声中的旧邮局|select','场景目标|交出关键线索，同时保留人物秘密。|area','主持工具|场景推进 / 时钟 / 战斗 / NPC|select','私密信息|最后一封信来自失踪的父亲。|area'],
 seat:['席位|玩家 3','控制方式|真人 / AI / 空席|select','角色卡|选择角色卡|select','邀请|生成本房间邀请入口','信息权限|公开信息与本人私密线索|select'],
 offline:['离线推进|开启|select','最多推进|3 天|select','暂停条件|重大关系、资源耗尽、剧情关键事件|area','返回反馈|日报与待确认变化|select'],
 'community-submit':['本地正式版本|雾港失踪案 v1.3|select','发行标题|雾港失踪案','价格|免费','许可与署名|保留作者与素材来源|area','更新说明|补齐地图署名与角色卡说明。|area'],
 moderate:['审核作品|潮汐镇的日常 v0.9','处理结果|退回补充|select','理由|请补齐公共设施参考素材的来源说明。|area','公开反馈|创作者可见|select'],
 support:['类别|申诉 / 发行支持 / 结算|select','关联发行|雾港失踪案 v1.3|select','问题说明|说明问题、时间与希望处理的结果。|area'],
 rating:['评分|5 星|select','游玩版本|v1.3','评价|线索安排清晰，人物对话有余味。|area']
};
if(specific[t])return <><div className="row-between"><Tag>{product.book}</Tag><small>{p.page.label}</small></div><Fields fields={specific[t]}/>{['settings','routing','preset','media-settings','local-model'].includes(t)&&<div className="inline-actions"><Btn modal="connection">测试与诊断</Btn><Btn modal="saved">保存预设</Btn></div>}</>;
return <><div className="row-between"><Tag>{product.book}</Tag><small>{p.page.label}</small></div><Fields fields={['名称|'+(p.page.label==='正文'?'海水退去以后':p.page.label),'当前内容|'+product.tagline+' 在这里调整选中对象的内容、范围与说明。|area','关联对象|当前作品|select','状态|待确认|select','备注|保留来源与已确认内容，说明本次变更。|area']}/><CheckList items={['内容已经检查','来源与使用范围已确认']}/></>;
}
