import BrandIcon from '../../src/components/shared/BrandIcon';
import {useEffect,useState} from 'react';
import{products,allPages,chapters}from'./catalog';
import{Icon,Tag}from'./ui';
import{renderView}from'./views';
import{Modal}from'./modal';
const initial=()=>{const [a,b]=location.hash.slice(1).split('/');return [a||'home',b||'today']};
export function PreviewApp({route:controlledRoute,onNavigate}:{route?:string[];onNavigate?:(route:string)=>void}){const[hashRoute,setRoute]=useState(initial);const route=controlledRoute??hashRoute;const[modal,setModal]=useState('');const[navigationOpen,setNavigationOpen]=useState(false);const[state,setState]=useState('常规');const[worlds,setWorlds]=useState<Record<string,boolean>>({});const[search,setSearch]=useState('');
useEffect(()=>{if(controlledRoute)return;const f=()=>{setRoute(initial());setModal('');document.querySelector('.main')?.scrollTo(0,0)};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[controlledRoute]);
const product=products.find(p=>p.id===route[0])||products[0];const page=product.pages.find(p=>p.id===route[1])||product.pages[0];const hasWorld=state==='未选世界'?false:state==='已选世界'?true:!!worlds[product.id];
const nav=(id:string)=>{if(onNavigate)onNavigate(id);else location.hash=id};
const groups=[...new Set(product.pages.map(p=>p.group))];
const currentStage=page.group.includes('S1')?'S1':page.group.includes('S2')?'S2':'S3';
return <><div className="public-preview-notice" role="note">{['adventure','openworld'].includes(product.id)?<><strong>尚在开发完善中，目前非正式功能</strong><span>{product.name}当前展示界面样式与示例内容，尚未接入正式功能。</span></>:<><strong>{onNavigate?"界面优化调整中":"新版 UI 预览 · 优化调整中"}</strong><span>{onNavigate?"当前页面为样式预览，作品与数据均为示例。":"UI 重构时功能出现混乱，正在梳理；梳理完成后上线。当前仅为示例预览。"}</span></>}{!onNavigate&&<a href={import.meta.env.BASE_URL}>返回正式版 <Icon name="ArrowRight" size={14}/></a>}</div><div className={`app ${navigationOpen?"preview-navigation-open":""}`} onClick={e=>{const el=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-modal],button[data-route]');if(el?.dataset.route)nav(el.dataset.route);else if(el?.dataset.modal){if(el.dataset.modal==='choose-world'){setWorlds({...worlds,[product.id]:true});setState('已选世界');}else setModal(el.dataset.modal)}}}>
<header className="topbar"><button className="brand" onClick={()=>nav('home/today')}><BrandIcon size={38}/><div><strong>StoryForge</strong><span>故事熔炉</span></div></button><nav className="global-nav" aria-label="产品导航">{products.filter(p=>p.id!=='community').map(p=><button key={p.id} onClick={()=>nav(`${p.id}/${p.pages[0].id}`)} className={p.id===product.id?'active':''}>{p.short}</button>)}</nav><div className="top-actions">{onNavigate&&<button className="mobile-preview-menu" aria-label="页面目录" aria-expanded={navigationOpen} onClick={()=>setNavigationOpen(!navigationOpen)}><Icon name="List"/></button>}<button aria-label="搜索" onClick={()=>nav('home/search')}><Icon name="Search"/></button><button aria-label="任务中心" onClick={()=>nav('home/tasks')}><Icon name="Clock"/></button><button className="avatar" onClick={()=>nav('home/settings')}>悬</button></div></header>
<aside className="sidebar"><div className="sidebar-title"><small>{product.en}</small><h2>{product.name}</h2><p>{product.tagline}</p></div>{product.id!=='home'&&<button className="current-work" onClick={()=>nav(`${product.id}/${product.pages[0].id}`)}><span className="work-glyph"><Icon name={product.id==='world'?'Globe2':'BookOpen'} size={22}/></span><span><strong>{product.book}</strong><small>{product.upper?'制作中的作品':'最近编辑 · 今天'}</small></span><Icon name="ChevronDown" size={14}/></button>}
<div className="side-scroll">{product.upper?<><button className={`side-module ${page.id==='source'?'active':''}`} onClick={()=>nav(`${product.id}/source`)}><Icon name="Globe2"/>世界引擎<span>S1</span></button><button className={`side-module ${page.group.includes('制作台')?'active':''}`} onClick={()=>nav(`${product.id}/vision`)}><Icon name="NotebookPen"/>制作台<span>S2–S3</span></button>{page.group.includes('制作台')&&groups.filter(g=>g.includes('制作台')).map(g=><section className="side-group compact" key={g}><h4>{g.endsWith('S2')?'S2 · 产品定向':'S3 · 产品执行'}</h4>{product.pages.filter(p=>p.group===g).map(p=><button key={p.id} className={p.id===page.id?'active':''} onClick={()=>nav(`${product.id}/${p.id}`)}>{p.label}</button>)}</section>)}<button className={`side-module ${page.id==='library'?'active':''}`} onClick={()=>nav(`${product.id}/${product.pages[0].id}`)}><Icon name="Library"/>作品库</button><button className={`side-module ${page.group==='游玩'?'active':''}`} onClick={()=>nav(`${product.id}/play`)}><Icon name="Play"/>游玩</button>{page.group==='游玩'&&<section className="side-group compact">{product.pages.filter(p=>p.group==='游玩').map(p=><button key={p.id} className={p.id===page.id?'active':''} onClick={()=>nav(`${product.id}/${p.id}`)}>{p.label}</button>)}</section>}</>:groups.map(g=><section className="side-group" key={g}><h4>{g}</h4>{product.pages.filter(p=>p.group===g).map(p=><button key={p.id} className={p.id===page.id?'active':''} onClick={()=>nav(`${product.id}/${p.id}`)}><Icon name={kindIcon(p.kind)}/>{p.label}</button>)}</section>)}{product.id==='long'&&page.id==='editor'&&<section className="side-group chapter-side"><h4>正文章节</h4>{chapters.map((x,i)=><button key={x} className={i===3?'active':''}>{x}</button>)}</section>}</div>
<footer className="sidebar-footer"><button onClick={()=>nav('community/discover')}><Icon name="Compass"/>社区与发行</button><button onClick={()=>nav('home/settings')}><Icon name="Settings"/>通用设置</button><p><Icon name="Feather" size={14}/> 让故事在此生长。</p></footer></aside>
<main className={`main product-${product.id} view-${page.kind}`}><div className="breadcrumb"><span>{product.name}</span><Icon name="ChevronRight" size={13}/><span>{page.label}</span><div className="breadcrumb-end">{product.upper?<><Tag tone={hasWorld?'green':'warm'}>{hasWorld?'雾海群岛 · v1.3':'尚未选择世界'}</Tag><button data-route={`${product.id}/source`}>查看来源</button></>:<><span className="status-dot"/>{onNavigate?"示例内容 · 未接入":"草稿已保存"}</>}</div></div>
{product.upper&&<div className="phase-path">{['S1 世界封存','S2 产品定向','S3 产品执行'].map((s,i)=><button key={s} className={currentStage===s.slice(0,2)?'active':''} onClick={()=>nav(`${product.id}/${['source','vision','production'][i]}`)}><span>{i+1}</span><strong>{s.slice(3)}</strong><small>{['准备与选择世界','讨论、配置与确认','制作、发布与运行'][i]}</small>{i<2&&<Icon name="ChevronRight" size={15}/>}</button>)}</div>}
{product.id==='long'&&page.id!=='library'&&<div className="shoulder-tabs">{[['分步骤','overview'],['节点模式','nodes'],['Agent 对话','agent']].map(([name,id])=><button key={id} className={(id===page.id||id==='overview'&&!['nodes','agent'].includes(page.id))?'active':''} onClick={()=>nav(`long/${id}`)}>{name}</button>)}</div>}
{renderView({product,page,state,hasWorld})}<div className="page-footer"><span>StoryForge · 样式初版 · 示例内容</span><span>{product.name} / {page.label}</span></div></main>
<div className="preview-toolbar"><span><i/> 样式预览</span><button onClick={()=>setModal('index')}><Icon name="LayoutGrid" size={14}/>全部页面 <b>{allPages.length}</b></button><span className="toolbar-sep"/><label>状态 <select aria-label="预览状态" value={state} onChange={e=>setState(e.target.value)}>{['常规','未选世界','已选世界','运行中','待确认','失败','版本过期','空白'].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>setModal('states')}>弹窗与状态</button></div>
{modal&&<Modal type={modal} product={product} page={page} close={()=>setModal('')} navigate={nav} query={search} setQuery={setSearch} hasWorld={hasWorld}/>}
</div></>}
function kindIcon(k:string){return ({home:'Home',library:'Library',source:'Globe2',world:'Globe2',form:'NotebookPen',characters:'Users',relations:'Network',outline:'List',scenes:'Layers',editor:'Feather',nodes:'GitBranch',agent:'MessageCircle',review:'ShieldCheck',timeline:'Clock',ledger:'FileText',map:'Map',media:'Image',versions:'Layers',script:'ScrollText',comic:'LayoutGrid',settings:'Settings',backup:'Save',import:'Upload',prompts:'Sparkles',style:'Feather',search:'Search',tasks:'Clock',cover:'BookOpen',pack:'Package',shots:'Image'} as Record<string,string>)[k]||'FileText'}

