import type { ReactNode } from 'react';
import {ArrowRight,Plus,ChevronDown,Check,MoreHorizontal,Sparkles,Search,FileText,Globe2,BookOpen,Users,Map,Layers,MessageCircle,Image,SlidersHorizontal,Clock,GitBranch,Play,Download,Upload,Settings,ShieldCheck,Compass,RefreshCw,Feather,Bookmark,Link,Music,Flag,AlertCircle,ChevronRight,Send,X,Folder,Pause,Volume2,Maximize,Save,Undo2,Redo2,Bold,Italic,List,Type,Target,Package,Swords,Heart,Coins,Sun,Leaf,Eye,Copy,Trash2,GripVertical,CheckCircle2,PanelRight,Home,LayoutGrid,Network,Library,ScrollText,NotebookPen,Info,Key} from 'lucide-react';
export const glyphs={ArrowRight,Plus,ChevronDown,Check,MoreHorizontal,Sparkles,Search,FileText,Globe2,BookOpen,Users,Map,Layers,MessageCircle,Image,SlidersHorizontal,Clock,GitBranch,Play,Download,Upload,Settings,ShieldCheck,Compass,RefreshCw,Feather,Bookmark,Link,Music,Flag,AlertCircle,ChevronRight,Send,X,Folder,Pause,Volume2,Maximize,Save,Undo2,Redo2,Bold,Italic,List,Type,Target,Package,Swords,Heart,Coins,Sun,Leaf,Eye,Copy,Trash2,GripVertical,CheckCircle2,PanelRight,Home,LayoutGrid,Network,Library,ScrollText,NotebookPen,Info,Key};
export function Icon({name='Feather',size=18}:{name?:string;size?:number}){const I=glyphs[name as keyof typeof glyphs]||Feather;return <I size={size} strokeWidth={1.6}/>}
const previewAssets=import.meta.glob('../assets/*',{eager:true,query:'?url',import:'default'}) as Record<string,string>;
export const asset=(name:string)=>previewAssets[`../assets/${name}`] || `${import.meta.env.BASE_URL}${name.startsWith('mist-')?'demo-assets/mist-harbor/':'prototypes/tidewake-town/media/'}${name}`;
export function Btn({children,primary=false,icon,modal,route,small=false}: {children?:ReactNode;primary?:boolean;icon?:string;modal?:string;route?:string;small?:boolean}){return <button className={`btn ${primary?'primary':''} ${small?'small':''}`} data-modal={modal} data-route={route}>{icon&&<Icon name={icon}/>} {children}</button>}
export function Tag({children,tone='green'}:{children:ReactNode;tone?:string}){return <span className={`tag ${tone}`}>{children}</span>}
export function Paper({children,className=''}:{children:ReactNode;className?:string}){return <section className={`paper ${className}`}>{children}</section>}
export function Note({title='创作札记',children,tone=''}:{title?:string;children:ReactNode;tone?:string}){return <aside className={`note ${tone}`}><header><h3>{title}</h3><Icon name="MoreHorizontal"/></header>{children}</aside>}
export function Field({label,value='',type='text',wide=false}:{label:string;value?:string;type?:string;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{type==='area'?<textarea defaultValue={value} rows={3}/>:type==='select'?<div className="select-field"><select defaultValue={value}><option>{value}</option><option>自定义设置</option></select><Icon name="ChevronDown" size={15}/></div>:<input defaultValue={value}/>}</label>}
export function Fields({fields}:{fields:string[]}){return <div className="fields">{fields.map((f,i)=>{const [label,value,type]=f.split('|');return <Field key={i} label={label} value={value} type={type} wide={type==='area'}/>})}</div>}
export function Heading({title,desc,eyebrow,action}:{title:string;desc?:string;eyebrow?:string;action?:ReactNode}){return <div className="heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{desc&&<p>{desc}</p>}</div>{action&&<div className="heading-actions">{action}</div>}</div>}
export function SectionTitle({title,children}:{title:string;children?:ReactNode}){return <header className="section-title"><h2>{title}</h2>{children}</header>}
export function Tabs({items,active=0}:{items:string[];active?:number}){return <div className="tabs">{items.map((x,i)=><button key={x} className={i===active?'active':''}>{x}</button>)}</div>}
export function Row({title,detail,status,icon='FileText',end}:{title:string;detail?:string;status?:string;icon?:string;end?:ReactNode}){return <div className="entry-row"><span className="icon-wash"><Icon name={icon}/></span><div className="entry-copy"><strong>{title}</strong>{detail&&<p>{detail}</p>}</div>{status&&<Tag>{status}</Tag>}{end||<Icon name="ChevronRight" size={17}/>}</div>}
export function Stats({items}:{items:[string,string][]}){return <div className="stats">{items.map(([v,k])=><div key={k}><strong>{v}</strong><span>{k}</span></div>)}</div>}
export function Progress({value=65}:{value?:number}){return <div className="progress"><i style={{width:`${value}%`}}/></div>}
export function CheckList({items}:{items:string[]}){return <div className="check-list">{items.map((x,i)=><label key={x}><input type="checkbox" defaultChecked={i<items.length-1}/><span>{x}</span></label>)}</div>}
export function Book({title='雾港纪事',image='mist-harbor.webp',small=false,index=0}:{title?:string;image?:string;small?:boolean;index?:number}){return <div className={`book ${small?'mini':''} book-${index%3}`} style={{backgroundImage:`linear-gradient(180deg,rgba(17,46,47,.15),rgba(13,38,44,.76)),url(${asset(image)})`}}><div className="book-rule"/><span className="book-kicker">STORYFORGE COLLECTION</span><strong>{title}</strong><span className="book-sub">潮水记得一切<br/>也会带走一切</span><span className="book-author">悬象 · 著</span><span className="book-bottom">故事熔炉</span></div>}
export function Table({heads,rows}:{heads:string[];rows:ReactNode[][]}){return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
export function Empty({title='故事还未开始',desc='从这里开始，给你的第一个想法留一个位置。'}:{title?:string;desc?:string}){return <Paper className="empty"><div className="empty-art"><Icon name="BookOpen" size={56}/><span>✦</span></div><h2>{title}</h2><p>{desc}</p><Btn primary icon="Plus" modal="create">开始创作</Btn></Paper>}
