import {test,expect} from '@playwright/test';
import {seedCurrentAiTownProduct} from './helpers/current-products';
test('AI 小镇：无世界可填写、跨页保存、刷新、来源与生产确认',async({page})=>{
 await page.goto('./town/vision');
 await page.getByLabel('小镇名称',{exact:true}).fill('海边的新生活');
 await page.getByLabel('生活愿景与开场目标').fill('和旧友一起修复茶屋');
 const nav=page.getByRole('navigation',{name:'AI 小镇内容导航',exact:true});
 await nav.getByRole('button',{name:'居民与地点',exact:true}).click();
 await expect(page).toHaveURL(/project=/);
 await page.getByLabel('居民数量（须与所选世界居民一致）').fill('4');
 await nav.getByRole('button',{name:'日程与生活规则',exact:true}).click();
 await page.reload();
 await expect(page.getByLabel('小镇名称',{exact:true})).toHaveValue('海边的新生活');
 await nav.getByRole('button',{name:'确认制作方案',exact:true}).click();
 await expect(page.getByRole('heading',{name:'开始制作，需要一个世界引擎'})).toBeVisible();
 await page.evaluate(async()=>{const load=new Function('p','return import(p)');await(await load('/storyforge/tests/helpers/current-product-world.ts')).seedCurrentProductWorld('可用小镇世界',{minimumCharacters:4});});
 await page.getByRole('button',{name:'选择世界引擎',exact:true}).click();
 await page.getByRole('button',{name:'选择此版本',exact:true}).first().click();
 await expect(page.getByText('世界版本已选择',{exact:true})).toBeVisible();
 await page.getByRole('navigation',{name:'AI 小镇页面导航',exact:true}).getByRole('button',{name:'制作台',exact:true}).click();
 await nav.getByRole('button',{name:'确认制作方案',exact:true}).click();
 await page.getByRole('button',{name:'生成或更新审查方案'}).click();
 await expect(page).toHaveURL(/town\/production/);
 await expect(page.getByText('审查方案已保存，核对后明确授权才会开始制作。')).toBeVisible();
 await page.reload();
 await expect(page.getByRole('button',{name:'回到方案确认'})).toBeVisible();
 const builds=await page.evaluate(async()=>{const load=new Function('p','return import(p)');return (await load('/storyforge/src/lib/db/schema.ts')).db.productBuilds.count();});expect(builds).toBe(0);
});
test('AI 小镇新游玩页面：对话、分区导航、存档与刷新',async({page})=>{
 const seeded=await seedCurrentAiTownProduct(page);
 await page.goto(`./town/play?project=${seeded.projectId}&session=${seeded.sessionId}`);
 await expect(page.getByTestId('ai-town-map')).toBeVisible();
 const player=page.getByTestId('ai-town-player');
 await player.getByRole('button',{name:/林舟.*calm/}).click();
 await player.getByPlaceholder('对林舟说……').fill('一起修茶屋吧');
 await player.getByRole('button',{name:'仅保存',exact:true}).click();
 await expect(player).toContainText('一起修茶屋吧');
 const nav=page.getByRole('navigation',{name:'AI 小镇内容导航',exact:true});
 await nav.getByRole('button',{name:'邻里与变化'}).click();
 await expect(player.getByRole('heading',{name:'可观察关系'})).toBeVisible();
 await expect(player.getByTestId('ai-town-map')).toBeHidden();
 await nav.getByRole('button',{name:'小镇档案'}).click();
 await player.getByRole('button',{name:'离线推进 1 日',exact:true}).click();
 await player.getByPlaceholder('检查点名称').fill('第二天');
 await player.getByPlaceholder('检查点名称').locator('xpath=following-sibling::button').click();
 await expect(player.getByRole('button',{name:/第二天/})).toBeVisible();
 await page.reload();
 await expect(player).toContainText('第 2 日');
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
 await page.screenshot({path:'/tmp/ai-town-mobile.png',fullPage:true});
});
test('AI 小镇：会谈候选经确认回填，制作产物按居民、日程和设施显示',async({page})=>{
 await page.goto('./town/vision');
 await page.getByLabel('小镇名称',{exact:true}).fill('候选确认小镇');
 await page.getByRole('button',{name:'保存制作方案',exact:true}).click();
 await expect(page).toHaveURL(/project=/);
 await page.evaluate(async()=>{
  const load=new Function('p','return import(p)');const {db}=await load('/storyforge/src/lib/db/schema.ts');
  const draft=await db.aiTownAuthoringDrafts.toCollection().first();const scope={projectId:draft.projectId,worldId:draft.worldId,workId:draft.workId};
  const {consultAiTownV1}=await load('/storyforge/src/lib/ai-town/consultation.ts');const settings=JSON.parse(draft.settingsJson);settings.town.sharedProjectConcept='把旧邮局修成公共书屋';
  await consultAiTownV1({scope,question:'修成书屋',runAI:async()=>JSON.stringify({answer:'建议一起修复公共书屋，请确认。',settings})});
 });
 const nav=page.getByRole('navigation',{name:'AI 小镇内容导航',exact:true});
 await nav.getByRole('button',{name:'方案会谈',exact:true}).click();
 await expect(page.getByRole('heading',{name:'待确认方案'})).toBeVisible();
 await page.getByRole('button',{name:'确认并回填制作方案'}).click();
 await expect(page.getByText('候选已回填，可在各配置页继续编辑')).toBeVisible();
 await nav.getByRole('button',{name:'居民与地点',exact:true}).click();
 await expect(page.getByLabel('共同建设目标')).toHaveValue('把旧邮局修成公共书屋');
 await page.reload();
 await expect(page.getByLabel('共同建设目标')).toHaveValue('把旧邮局修成公共书屋');
 await page.screenshot({path:'/tmp/ai-town-author-desktop.png',fullPage:true});
 const seeded=await seedCurrentAiTownProduct(page);
 await page.goto(`./town/characters?project=${seeded.projectId}`);
 await expect(page.locator('summary').filter({hasText:/^林舟$/})).toBeVisible();
 await nav.getByRole('button',{name:'日程与事件',exact:true}).click();
 await expect(page.getByRole('heading',{name:'生活事件',exact:true})).toBeVisible();
 await nav.getByRole('button',{name:'小镇与设施',exact:true}).click();
 await expect(page.locator('summary').filter({hasText:/^茶屋$/})).toBeVisible();
 await page.screenshot({path:'/tmp/ai-town-inspector-desktop.png',fullPage:true});
});
