import { expect, test } from '@playwright/test'

test('longform library creates a real work and retains edits across navigation and reload', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('storyforge_guide_completed', 'e2e'))
  await page.goto('./long')
  await page.getByRole('button', { name: '新建长篇', exact: true }).click()
  await page.getByRole('textbox', { name: '新长篇名称' }).fill('青港长篇验收')
  await page.getByRole('button', { name: '创建并进入工作台' }).click()
  await expect(page.getByRole('navigation', { name: '长篇工作台二级导航' })).toBeVisible()
  const workUrl = page.url()
  const name = page.locator('input').filter({ visible: true }).first()
  await name.fill('青港长篇验收·修订')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await page.getByRole('navigation', { name: '长篇工作台二级导航' }).getByRole('button', { name: '世界与设定', exact: true }).click()
  await page.getByRole('navigation', { name: '世界与设定三级导航' }).getByRole('button', { name: '世界起源', exact: true }).click()
  await expect(page).toHaveURL(/module=worldview-origin/)
  await page.reload()
  await expect(page.getByRole('navigation', { name: '世界与设定三级导航' }).getByRole('button', { name: '世界起源', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('.lf-current')).toContainText('青港长篇验收·修订')
  const primary = page.getByRole('navigation', { name: '长篇一级导航' })
  await primary.getByRole('button', { name: '版本与导出', exact: true }).click()
  await page.getByRole('navigation', { name: '版本与导出', exact: true }).getByRole('button', { name: '导出与备份', exact: true }).click()
  await expect(page).toHaveURL(/module=export/)
  await primary.getByRole('button', { name: '派生世界', exact: true }).click()
  await expect(page.getByRole('button', { name: '派生世界草稿', exact: true })).toBeVisible()
  await primary.getByRole('button', { name: '社区与发行', exact: true }).click()
  await expect(page.getByText('当前分享方式为本地世界文件包。', { exact: false })).toBeVisible()
  await primary.getByRole('button', { name: '长篇工作台', exact: true }).click()
  await page.getByRole('navigation', { name: '工作台创作方式' }).getByRole('button', { name: '节点创作', exact: true }).click()
  await expect(page).toHaveURL(/module=visual-workflows/)
  await page.getByRole('navigation', { name: '工作台创作方式' }).getByRole('button', { name: 'Agent', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '告诉主 Agent 你的目标' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('textbox', { name: '告诉主 Agent 你的目标' })).toBeVisible()
  await primary.getByRole('button', { name: '作品库', exact: true }).click()
  await expect(page.getByRole('heading', { name: '青港长篇验收·修订', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '进入长篇工作台', exact: true }).click()
  await expect(page).toHaveURL(workUrl)
})

test('Agent discussion and proposed plan survive reload without starting production', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('storyforge_guide_completed', 'e2e')
    localStorage.setItem('storyforge-ai-config', JSON.stringify({ provider: 'openai', baseUrl: 'https://longform-test.invalid/v1', model: 'gpt-4o', temperature: 0.2, maxTokens: 4000 }))
    sessionStorage.setItem('storyforge-ai-api-key-session', 'isolated-test-key')
  })
  let calls = 0
  await page.route('https://longform-test.invalid/**', async route => {
    calls++
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ choices: [{ message: { role: 'assistant', content: JSON.stringify({ summary: '先创建一名寻找旧信的主角，等待作者确认。', tasks: [{ id: 'hero', agentId: 'character', instruction: '创建一名寻找旧信的主角', dependsOn: [] }] }) }, finish_reason: 'stop' }], usage: { prompt_tokens: 100, completion_tokens: 80, total_tokens: 180 } }) })
  })
  await page.goto('./long')
  await page.getByRole('button', { name: '新建长篇', exact: true }).click()
  await page.getByRole('textbox', { name: '新长篇名称' }).fill('会谈隔离验收')
  await page.getByRole('button', { name: '创建并进入工作台' }).click()
  await page.getByRole('navigation', { name: '工作台创作方式' }).getByRole('button', { name: 'Agent', exact: true }).click()
  await page.getByRole('textbox', { name: '告诉主 Agent 你的目标' }).fill('我们先讨论一名寻找旧信的主角，暂时不要生成。')
  await page.getByRole('button', { name: '讨论与规划', exact: true }).click()
  await expect(page.getByRole('button', { name: '确认计划并开始', exact: true })).toBeVisible()
  expect(calls).toBe(1)
  await page.reload()
  await expect(page.getByRole('button', { name: '确认计划并开始', exact: true })).toBeVisible()
  expect(calls).toBe(1)
  await page.getByText('整理需求摘要', { exact: true }).click()
  await page.getByRole('textbox', { name: '已确认的需求摘要', exact: true }).fill('修改方向：主角寻找的是旧日航图，暂不创建角色。')
  await page.getByRole('button', { name: '确认保存需求摘要', exact: true }).click()
  await expect(page.getByRole('button', { name: '确认计划并开始', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('textbox', { name: '告诉主 Agent 你的目标' })).toBeVisible()
  await expect(page.getByRole('button', { name: '确认计划并开始', exact: true })).toHaveCount(0)
  expect(calls).toBe(1)
  await page.getByRole('navigation', { name: '工作台创作方式' }).getByRole('button', { name: '分步骤模式', exact: true }).click()
  await page.getByRole('navigation', { name: '长篇工作台二级导航' }).getByRole('button', { name: '人物与关系', exact: true }).click()
  await expect(page.getByRole('button', { name: '采纳', exact: true })).toHaveCount(0)
})

test('chunked outline choices and formal candidates survive reload and adopt into their selected volume', async ({ page }) => {
  test.setTimeout(90000)
  await page.addInitScript(() => {
    localStorage.setItem('storyforge_guide_completed', 'e2e')
    localStorage.setItem('storyforge-ai-config', JSON.stringify({ provider: 'ollama', baseUrl: 'https://longform-chunked.invalid/v1', model: 'chunked-e2e', temperature: 0.2, maxTokens: 4000 }))
  })
  let directionCalls = 0
  let chapterCalls = 0
  await page.route('https://longform-chunked.invalid/**', async route => {
    const body = route.request().postDataJSON()
    const text = body.messages.map((message: { content: string }) => message.content).join('\n')
    let content: string
    if (text.includes('专业的小说结构师')) {
      directionCalls++
      content = JSON.stringify({ title: `旧信的方向${directionCalls}`, coreConflict: '主角寻找旧信来源，邮差阻止他查验。', characterChange: '从迟疑到决意', keyEvents: ['收到旧信', '查验邮戳'], mainNarrativeTrack: '寻找亲人', tension: 6 })
    } else {
      chapterCalls++
      const match = text.match(/为第 (\d+)-(\d+) 章生成 (\d+) 章/)
      expect(match).not.toBeNull()
      content = JSON.stringify(Array.from({ length: Number(match![3]) }, (_, index) => ({ title: `旧信第${Number(match![1]) + index}章`, summary: '主角追寻旧信的来源，面对邮差的隐瞒，发现下一条线索。' })))
    }
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ choices: [{ message: { content }, finish_reason: 'stop' }], usage: { prompt_tokens: 100, completion_tokens: 120, total_tokens: 220 } }) })
  })
  await page.goto('./long')
  await page.getByRole('button', { name: '新建长篇', exact: true }).click()
  await page.getByRole('textbox', { name: '新长篇名称' }).fill('精细章纲浏览器验收')
  await page.getByRole('button', { name: '创建并进入工作台' }).click()
  await page.getByRole('navigation', { name: '长篇工作台二级导航' }).getByRole('button', { name: '大纲与章纲', exact: true }).click()
  await page.getByRole('button', { name: '添加卷', exact: true }).click()
  await page.getByRole('button', { name: '生成本卷所有章节', exact: true }).click()
  await page.getByRole('button', { name: /^精细生成/ }).click()
  await page.getByRole('spinbutton', { name: '本卷章节数', exact: true }).fill('20')
  await page.locator('input[type="range"][min="3"]').fill('3')
  await page.getByRole('button', { name: '确认生成', exact: true }).click()
  await expect(page.getByRole('button', { name: '选定此方案', exact: true })).toBeVisible()
  expect(directionCalls).toBe(1); expect(chapterCalls).toBe(0)
  await page.reload()
  await page.getByRole('button', { name: '继续精细生成', exact: true }).click()
  await page.getByRole('button', { name: '选定此方案', exact: true }).click()
  await expect(page.getByText('《旧信的方向2》', { exact: true }).first()).toBeVisible()
  expect(chapterCalls).toBe(1)
  await page.reload()
  const callsBefore = directionCalls + chapterCalls
  await expect(page.getByRole('button', { name: '继续精细生成', exact: true })).toBeVisible()
  expect(directionCalls + chapterCalls).toBe(callsBefore)
  await page.getByRole('button', { name: '继续精细生成', exact: true }).click()
  await page.getByRole('button', { name: '选定此方案', exact: true }).click()
  await expect(page.getByText('《旧信的方向3》', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '选定此方案', exact: true }).click()
  await page.getByRole('button', { name: '采纳这些章纲', exact: true }).click()
  await expect(page.getByRole('button', { name: /^(正在采纳…|采纳这些章纲)$/ })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '章节列表（20 章）', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '编辑章节', exact: true })).toHaveCount(20)
  await page.reload()
  await expect(page.getByRole('heading', { name: '章节列表（20 章）', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '编辑章节', exact: true })).toHaveCount(20)
  expect(directionCalls).toBe(3); expect(chapterCalls).toBe(3)
})


test('narrow longform workspace keeps the editor usable and offers both navigation levels', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => localStorage.setItem('storyforge_guide_completed', 'e2e'))
  await page.goto('./long')
  await page.getByRole('button', { name: '新建长篇', exact: true }).click()
  await page.getByRole('textbox', { name: '新长篇名称' }).fill('窄屏长篇验收')
  await page.getByRole('button', { name: '创建并进入工作台' }).click()
  await expect(page.getByRole('button', { name: '分步骤目录', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '基本信息', exact: true })).toBeVisible()
  const content = await page.locator('.lf-content').boundingBox()
  expect(content!.width).toBeGreaterThan(330)
  await page.getByRole('button', { name: '分步骤目录', exact: true }).click()
  await page.getByRole('navigation', { name: '长篇工作台二级导航' }).getByRole('button', { name: '故事设计', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '长篇工作台二级导航' })).toBeHidden()
  await page.getByRole('button', { name: '长篇导航', exact: true }).click()
  await page.getByRole('navigation', { name: '长篇一级导航' }).getByRole('button', { name: '作品库', exact: true }).click()
  await expect(page.getByRole('heading', { name: '窄屏长篇验收', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.body.scrollWidth)).toBe(390)
})
