import { expect, test } from '@playwright/test'
async function create(page:import('@playwright/test').Page,mode='import'){
 await page.addInitScript(()=>localStorage.setItem('storyforge_guide_completed','e2e'))
 await page.goto('./motion/library')
 await page.getByRole('button',{name:'新建素材项目',exact:true}).click()
 await page.getByLabel('漫剧素材名称',{exact:true}).fill('E2E Seedance 素材')
 await page.getByLabel('来源方式',{exact:true}).selectOption(mode)
 await page.getByLabel('计划集数',{exact:true}).fill('1')
 await page.getByLabel('单集目标秒数',{exact:true}).fill('20')
 if(mode==='import')await page.getByLabel('导入原作内容',{exact:true}).fill('午夜，林岚拾起妹妹留下的旧车票。检票钳自行咬下，熄灭三年的站台灯逐盏亮向隧道，车窗里出现了妹妹。')
 else await page.getByLabel('一句话故事',{exact:true}).fill('检票员从旧车票听见妹妹未完成的告别。')
 await page.getByRole('button',{name:'创建漫剧素材',exact:true}).click()
 await expect(page.getByTestId('motion-drama-studio')).toBeVisible()
}
test('漫剧素材独立入口、无作品浏览与内容分类',async({page})=>{
 await page.goto('./motion/library')
 await expect(page.getByRole('navigation',{name:'产品导航'}).getByRole('link',{name:'漫剧素材',exact:true})).toBeVisible()
 const nav=page.getByRole('navigation',{name:'漫剧素材页面导航'})
 for(const label of ['作品库','漫剧制作台','版本与交付','通用设置'])await expect(nav.getByRole('button',{name:label,exact:true})).toBeVisible()
 await nav.getByRole('button',{name:'漫剧制作台',exact:true}).click()
 await expect(page.getByRole('navigation',{name:'漫剧素材内容分类'}).getByRole('button',{name:'参考帧',exact:true})).toBeVisible()
 await expect(page.getByText('尚未选择漫剧素材，可以浏览全部页面。',{exact:false})).toBeVisible()
 await expect(nav.getByRole('button',{name:'生成',exact:true})).toHaveCount(0)
})
test('一句话仍先建立小说来源，不冒充已完成素材',async({page})=>{
 await create(page,'premise')
 const studio=page.getByTestId('motion-drama-studio')
 await expect(studio.getByText('先完成小说，再进入漫剧改编',{exact:true})).toBeVisible()
 await studio.getByRole('button',{name:'创作 / 修改来源小说',exact:true}).click()
 await expect(studio.getByTestId('short-novel-studio')).toBeVisible()
 await page.getByRole('navigation',{name:'漫剧素材内容分类'}).getByRole('button',{name:'系列设定',exact:true}).click()
 await expect(studio.getByRole('button',{name:'生成专业候选',exact:true})).toBeDisabled()
})
test('实际单集素材、三种参考帧、编辑草稿恢复与交付 ZIP',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write'])
 await create(page)
  const compiled = await page.evaluate(async () => {
    const importer = new Function('path', 'return import(path)') as (path: string) => Promise<any>
    const { db } = await importer('/storyforge/src/lib/db/schema.ts')
    const { listActiveSourceUnits } = await importer('/storyforge/src/lib/adaptation/source-manifest.ts')
    const service = await importer('/storyforge/src/lib/motion-drama/service.ts')
    const packs = await importer('/storyforge/src/lib/motion-drama/prompt-pack.ts')
    const adaptation = (await db.adaptationProjects.toArray()).find((row: any) => row.medium === 'motion-drama')
    const work = (await db.works.toArray()).find((row: any) => row.kind === 'motion-drama')
    const scope = { projectId: adaptation.projectId, worldId: adaptation.worldId, workId: work.id }
    const sourceUnitKey = (await listActiveSourceUnits(adaptation.id)).find((row: any) => row.sourceKind === 'chapter').sourceUnitKey
    const adopt = async (stage: string, payload: unknown) => {
      const studio = await service.loadMotionDramaStudioV1(scope)
      await service.adoptMotionDramaCandidateV1({ scope, stage, payload, episodeNumber: 1, expectedAdaptationRevision: studio.adaptation.revision, expectedProductionRevision: studio.production.revision })
    }
    await adopt('series-bible', {
      version: 1, titlePromise: '旧车票会让未完成的告别重新上车。', logline: '夜班检票员必须在末班车消失前决定是否追上死去的妹妹。', coreTheme: '接受失去不是遗忘。', emotionalPromise: '悬疑中的克制治愈。', audiencePromise: '每集一次异常回声与一个不可逆选择。', storyEngine: '旧票触发回声，选择真相就会失去一段记忆。', worldRules: ['回声只在末班车前出现。'], seasonArc: '林岚从追索妹妹到接受告别。', protagonistArc: '从控制失去到承担失去。', relationshipArcs: ['姐妹误解逐集反转。'], episodeArchitecture: '异常冷开场，压力升级，代价尾钩。', hookPatterns: ['物件异常'], visualLanguage: ['冷蓝现实与琥珀回声'], soundLanguage: ['检票钳声触发能力'], continuityRules: ['左眉旧伤固定。'], productionConstraints: ['单镜不超过十秒。'],
    })
    await adopt('asset-bible', [{ stableKey: 'character.linlan', kind: 'character', label: '林岚', identity: '28岁东亚女性，左眉旧伤。', appearance: '黑色短发，克制警觉。', palette: ['冷蓝'], materials: ['湿呢料'], continuityLocks: ['左眉旧伤', '右手持钳'], prohibitedChanges: ['左右翻转'], basePrompt: '二维漫剧角色设定，林岚，左眉旧伤。', negativePrompt: '换脸，换装。', referenceBrief: '正侧面与持钳姿态。', sourceUnitKeys: [sourceUnitKey] }, { stableKey: 'voice.linlan', kind: 'voice', label: '林岚音色', identity: '成年女声，低沉克制。', appearance: '中低音区。', palette: [], materials: [], continuityLocks: ['普通语速'], prohibitedChanges: ['幼态'], basePrompt: '中低音区克制女声。', negativePrompt: '播音腔。', referenceBrief: '干声试听。', sourceUnitKeys: [sourceUnitKey] }, { stableKey: 'sound.ticket', kind: 'sound', label: '检票钳声', identity: '金属咔哒后接隧道低频。', appearance: '短促近场瞬态。', palette: [], materials: ['金属'], continuityLocks: ['音色固定'], prohibitedChanges: ['卡通音效'], basePrompt: '金属检票钳咔哒。', negativePrompt: '爆音。', referenceBrief: '两秒干净试听。', sourceUnitKeys: [sourceUnitKey] }])
    await adopt('episode-outline', { stableKey: 'episode.1', episodeNumber: 1, title: '妹妹的车票', logline: '旧车票召回妹妹的声音。', synopsis: '车票启动回声，神秘列车进站。', openingHook: '检票钳无人触碰却自行合拢。', beats: [{ stableKey: 'episode.1.beat.1', order: 0, function: 'hook', visibleAction: '检票钳咬穿车票。', conflict: '林岚想丢票却听见妹妹。', turn: '车票显出妹妹姓名。', targetSeconds: 10, sourceUnitKeys: [sourceUnitKey] }, { stableKey: 'episode.1.beat.2', order: 1, function: 'cliffhanger', visibleAction: '站台灯亮向隧道。', conflict: '列车即将进站。', turn: '车窗内坐着妹妹。', targetSeconds: 10, sourceUnitKeys: [sourceUnitKey] }], endHook: '妹妹隔窗抬眼。', continuityIn: [], continuityOut: ['神秘列车进站。'], sourceUnitKeys: [sourceUnitKey] })
    await adopt('episode-script', [{ stableKey: 'episode.1.scene.1', episodeNumber: 1, sceneNumber: 1, order: 0, heading: '内景·封闭站台·午夜', location: '废弃站台', timeOfDay: '午夜', dramaticPurpose: '异常物件召回妹妹。', entryState: '林岚独自巡检。', exitState: '神秘列车进站。', visibleAction: '检票钳自行合拢，林岚抬头看见列车。', dialogue: [{ speakerKey: 'character.linlan', text: '不可能。', delivery: '压住颤抖', estimatedSeconds: 2 }], narration: '', soundCues: [{ kind: 'sfx', cue: '检票钳声', timing: '动作点', subjectKey: 'sound.ticket' }], emotionalTurn: '冷静被恐惧击穿。', estimatedSeconds: 20, characterKeys: ['character.linlan'], sourceUnitKeys: [sourceUnitKey] }])
    const base = { episodeNumber: 1, sceneKey: 'episode.1.scene.1', narrativeFunction: '用异常推动悬疑', targetSeconds: 10, cameraAngle: 'eye-level', cameraMovement: 'dolly', performance: '呼吸变浅，目光由车票抬向隧道。', lighting: '冷蓝顶灯与琥珀逆光。', narration: '', soundPlan: [{ kind: 'sfx', cue: '检票钳咔哒', timing: '动作同步', subjectKey: 'sound.ticket' }], subjectKeys: ['character.linlan'], sourceUnitKeys: [sourceUnitKey], imagePrompt: '', negativeImagePrompt: '', firstFramePrompt: '', keyFramePrompt: '', lastFramePrompt: '', videoPrompt: '', negativeVideoPrompt: '' }
    await adopt('shot-design', [{ ...base, stableKey: 'episode.1.shot.1', shotNumber: 1, order: 0, shotSize: 'close-up', composition: '手与车票占前景，林岚虚焦在后。', visibleAction: '检票钳自行咬穿旧车票。', transitionIn: 'cut', transitionOut: 'match-cut', dialogue: '林岚：不可能。' }, { ...base, stableKey: 'episode.1.shot.2', shotNumber: 2, order: 1, shotSize: 'medium', composition: '林岚在左侧三分线，隧道光从右后逼近。', visibleAction: '林岚抬头，列车窗内显出妹妹。', transitionIn: 'match-cut', transitionOut: 'cut', dialogue: '' }])
    let studio = await service.loadMotionDramaStudioV1(scope)
    await adopt('image-prompts', studio.shots.map((shot: any) => ({ shotKey: shot.stableKey, expectedRevision: shot.revision, imagePrompt: `${shot.visibleAction}，电影化二维漫剧。`, negativeImagePrompt: '换脸，额外肢体，文字，水印。', firstFramePrompt: `${shot.visibleAction}前的稳定动作起点。`, keyFramePrompt: `${shot.visibleAction}的动作峰值。`, lastFramePrompt: `${shot.visibleAction}后的稳定停点。` })))
    studio = await service.loadMotionDramaStudioV1(scope)
    await adopt('video-prompts', studio.shots.map((shot: any) => ({ shotKey: shot.stableKey, expectedRevision: shot.revision, videoPrompt: `从稳定姿态开始，${shot.visibleAction}，环境光响应，摄影机缓慢推进，动作落到停点。`, negativeVideoPrompt: '抽搐，融化，瞬移，循环，镜头乱摆。' })))
    const png = new Uint8Array(32); png.set([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]); new DataView(png.buffer).setUint32(16, 1024); new DataView(png.buffer).setUint32(20, 1536)
    const wav = new Uint8Array(44); wav.set([82, 73, 70, 70], 0); wav.set([87, 65, 86, 69], 8); wav.set([102, 109, 116, 32], 12); wav.set([100, 97, 116, 97], 36)
    const rights = () => ({ version: 1, source: 'author-upload', commercialUse: 'allowed', redistribution: 'allowed', attribution: '', declaration: 'E2E 测试拥有完整商用与再分发权利。', declaredAt: Date.now() })
    await service.commitMotionDramaAssetReferenceV1({ scope, subjectKey: 'character.linlan', data: png.buffer, rights: rights() })
    await service.commitMotionDramaAssetReferenceV1({ scope, subjectKey: 'voice.linlan', data: wav.buffer, rights: rights() })
    await service.commitMotionDramaAssetReferenceV1({ scope, subjectKey: 'sound.ticket', data: wav.buffer, rights: rights() })
    studio = await service.loadMotionDramaStudioV1(scope)
    for (const shot of studio.shots) await service.commitMotionDramaShotReferenceV1({ scope, shotKey: shot.stableKey, role: 'start-frame', data: png.buffer, rights: rights() })
    studio = await service.loadMotionDramaStudioV1(scope)
    const row = await packs.compileMotionDramaPromptPackV1({ scope, episodeNumber: 1, provider: 'seedance', providerProfileId: 'seedance-2.5-2026-07', expectedProductionRevision: studio.production.revision })
    const manifest = await packs.verifyMotionDramaPromptPackV1(row)
    return { version: manifest.version, directUseReady: manifest.directUseReady }
  })
  expect(compiled).toEqual({ version: 2, directUseReady: true })


 const rootUrl=page.url().split('/source?')[0]
 const work=new URL(page.url()).searchParams.get('work')!
 await page.goto(`${rootUrl}/pack?work=${work}`)
 const studio=page.getByTestId('motion-drama-studio')
 await expect(studio.getByRole('heading',{name:'逐镜生成、选片与交接运行单',exact:true})).toBeVisible()
 await studio.getByRole('button',{name:'复制镜头 1 Seedance 提示词',exact:true}).click()
 expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('上传槽位')
 await page.goto(`${rootUrl}/frames?work=${work}`)
 await expect(studio.getByLabel('上传镜头 1 起始帧',{exact:true})).toBeDisabled()
 await studio.getByRole('checkbox').check()
 for(const role of ['起始帧','关键帧','结束帧'])await expect(studio.getByLabel(`上传镜头 1 ${role}`,{exact:true})).toBeEnabled()
 // Supply a valid PNG through the UI, not a provider request.
 await studio.getByLabel('上传镜头 1 关键帧',{exact:true}).setInputFiles({name:'key.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5ncAAAAASUVORK5CYII=','base64')})
 await expect(studio.getByRole('img',{name:'镜头 1 关键帧',exact:true})).toBeVisible()
 await page.goto(`${rootUrl}/series?work=${work}`)
 await studio.getByRole('button',{name:'编辑本页内容',exact:true}).click()
 await page.getByLabel('内容 · 核心主题',{exact:true}).fill('作者修改后的主题，刷新保留。')
 await expect(page.getByRole('status')).toContainText('编辑草稿已保存')
 await page.reload()
 await studio.getByRole('button',{name:'编辑本页内容',exact:true}).click()
 await expect(page.getByLabel('内容 · 核心主题',{exact:true})).toHaveValue('作者修改后的主题，刷新保留。')
 await page.getByRole('button',{name:'确认写入',exact:true}).click()
 await expect(page.locator('.motion-candidate')).toHaveCount(0)
 await page.goto(`${rootUrl}/versions?work=${work}`)
 await expect(studio.getByRole('button',{name:'保存提示词交付版',exact:true})).toBeDisabled()
 await page.goto(`${rootUrl}/pack?work=${work}`)
 await studio.getByRole('button',{name:'编译适配包',exact:true}).first().click()
 await expect(studio.getByText('可直接投喂',{exact:true}).last()).toBeVisible()
 await page.goto(`${rootUrl}/versions?work=${work}`)
 await studio.getByRole('button',{name:'保存含参考素材交付版',exact:true}).click()
 await expect(studio.getByRole('button',{name:'下载提示词与素材 ZIP',exact:true})).toBeVisible()
 const download=page.waitForEvent('download')
 await studio.getByRole('button',{name:'下载提示词与素材 ZIP',exact:true}).click()
 expect((await download).suggestedFilename()).toMatch(/\.zip$/)
 await page.screenshot({path:'/tmp/motion-materials-delivery.png',fullPage:true})
 await page.goto(`${rootUrl}/frames?work=${work}`)
 await expect(studio.locator('label.motion-upload').filter({has:page.getByLabel('上传镜头 1 起始帧',{exact:true})})).toBeVisible()
 await page.screenshot({path:'/tmp/motion-materials-frames.png',fullPage:true})
})
