import { expect, test } from '@playwright/test'

test('screenplay product UI creates from imported text, plans, edits, reviews, publishes and exports',async({page})=>{
 test.setTimeout(120000)
 await page.addInitScript(()=>localStorage.setItem('storyforge_guide_completed','e2e'))
 await page.goto('./script/library')
 await page.getByRole('button',{name:'新建剧本改编',exact:true}).click()
 await page.getByLabel('剧本名称',{exact:true}).fill('车站改编 UI 验收')
 await page.getByLabel('来源方式',{exact:true}).selectOption('import')
 await page.getByLabel('导入原作内容').fill('林岚走进车站。末班车即将离开，她选择留下等待弟弟。')
 await page.getByLabel('单集目标分钟',{exact:true}).fill('1')
 await page.getByRole('button',{name:'冻结来源并创建剧本',exact:true}).click()
 await expect(page).toHaveURL(/script\/source\?work=\d+/)
 const nav=page.getByRole('navigation',{name:'剧本页面导航',exact:true})
 const sub=page.getByRole('navigation',{name:'页面内导航',exact:true})
 await sub.getByRole('button',{name:'原作事实',exact:true}).click()
 await page.getByRole('button',{name:'添加原作事实',exact:true}).click()
 await page.getByLabel('第1项 原作事实',{exact:true}).fill('林岚走进车站。')
 await page.getByRole('button',{name:'添加原作事实',exact:true}).click()
 await page.getByLabel('第2项 原作事实',{exact:true}).fill('她选择留下等待弟弟。')
 await page.getByRole('button',{name:'确认原作事实',exact:true}).click()
 await expect(page.getByRole('alert')).toHaveCount(0)
 await sub.getByRole('button',{name:'因果关系',exact:true}).click()
 await page.getByRole('button',{name:'添加因果关系',exact:true}).click()
 await page.getByLabel('第1项 取舍理由',{exact:true}).fill('到站让她必须决定是否上车。')
 await page.getByRole('button',{name:'确认因果关系',exact:true}).click()
 await nav.getByRole('button',{name:'改编目标',exact:true}).click()
 await page.getByLabel('核心主题',{exact:true}).fill('等待与选择')
 await page.getByLabel('主导情绪',{exact:true}).fill('克制的希望')
 await page.getByRole('button',{name:'确认改编要求',exact:true}).click()
 await sub.getByRole('button',{name:'删改决定',exact:true}).click()
 await page.getByRole('button',{name:'添加删改决定',exact:true}).click()
 await page.getByLabel('第1项 取舍理由',{exact:true}).fill('保留车站和最后的选择。')
 await page.getByRole('button',{name:'确认删改决定',exact:true}).click()
 await nav.getByRole('button',{name:'结构与节拍',exact:true}).click()
 await page.getByRole('button',{name:'添加结构与节拍',exact:true}).click()
 for(const [label,value] of [['叙事目标','找到弟弟'],['冲突与阻力','列车即将离开'],['转折','选择留下'],['结果','停在站台']])await page.getByLabel('第1项 '+label,{exact:true}).fill(value)
 await page.getByRole('button',{name:'确认结构与节拍',exact:true}).click()
 await nav.getByRole('button',{name:'场次目录',exact:true}).click()
 await page.getByRole('button',{name:'添加场次卡片',exact:true}).click()
 for(const [label,value] of [['场次目的','作出选择'],['冲突与阻力','末班车催促'],['入场状态','匆忙到站'],['离场状态','决定留下'],['可见行动','林岚停在站台，转身望向入口。'],['信息揭示','她在等待弟弟']])await page.getByLabel('第1项 '+label,{exact:true}).fill(value)
 await page.getByRole('button',{name:'确认场次卡片',exact:true}).click()
 await page.getByRole('button',{name:'进入场景生产',exact:true}).click()
 await nav.getByRole('button',{name:'剧本编辑',exact:true}).click()
 await page.getByRole('button',{name:'从下一张 Scene Card 新建',exact:true}).click()
 await page.getByPlaceholder('地点',{exact:true}).fill('旧车站')
 // Switching pages preserves an unconfirmed editor draft rather than discarding it.
 await nav.getByRole('button',{name:'原作一致性',exact:true}).click()
 await nav.getByRole('button',{name:'剧本编辑',exact:true}).click()
 await expect(page.getByPlaceholder('地点',{exact:true})).toHaveValue('旧车站')
 await page.reload()
 await expect(page.getByPlaceholder('地点',{exact:true})).toHaveValue('旧车站')
 await page.getByRole('button',{name:'保存场景',exact:true}).click()
 await expect(page.getByRole('alert')).toHaveCount(0)
 await nav.getByRole('button',{name:'原作一致性',exact:true}).click()
 await page.getByRole('button',{name:'作者确认来源无问题',exact:true}).click()
 await nav.getByRole('button',{name:'戏剧性审校',exact:true}).click()
 await page.getByRole('button',{name:'作者确认戏剧无问题',exact:true}).click()
 await nav.getByRole('button',{name:'剧本编辑',exact:true}).click()
 await page.getByRole('button',{name:'标记已审定',exact:true}).click()
 await nav.getByRole('button',{name:'版本与导出',exact:true}).click()
 await expect(page.getByRole('button',{name:'发布不可变版本',exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'发布不可变版本',exact:true}).click()
 await expect(page.getByRole('button',{name:'已发布 v1',exact:true})).toBeVisible()
 const download=page.waitForEvent('download')
 await page.getByRole('button',{name:'Fountain',exact:true}).click()
 expect((await download).suggestedFilename()).toMatch(/\.fountain$/)
 await page.reload()
 await expect(page.getByRole('button',{name:'已发布 v1',exact:true})).toBeVisible()
 await nav.getByRole('button',{name:'剧本编辑',exact:true}).click()
 await expect(page.getByPlaceholder('地点',{exact:true})).toBeDisabled()
 await page.screenshot({path:'/tmp/storyforge-screenplay-live-editor.png',fullPage:true})
 await page.locator('.screenplay-layout').screenshot({path:'/tmp/storyforge-screenplay-editing-surface.png'})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'/tmp/storyforge-screenplay-live-mobile.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('every screenplay page is open without a work and does not create data merely by browsing',async({page})=>{
 for(const id of ['library','source','brief','structure','scenes','editor','grounding','review','versions']){
  await page.goto('./script/'+id)
  await expect(page.getByRole('navigation',{name:'剧本页面导航'})).toBeVisible()
  await expect(page.getByTestId('approved-product-ui')).toHaveCount(0)
 }
})

test('screenplay AI candidate edits and excluded items survive refresh before adoption',async({page})=>{
 await page.addInitScript(()=>{
  localStorage.setItem('storyforge_guide_completed','e2e')
  localStorage.setItem('storyforge-ai-config',JSON.stringify({provider:'openai',baseUrl:'https://screenplay-test.invalid/v1',model:'gpt-4o',temperature:0.2,maxTokens:4000}))
  sessionStorage.setItem('storyforge-ai-api-key-session','isolated-test-key')
 })
 let calls=0
 await page.route('https://screenplay-test.invalid/**',async route=>{
  calls++;const request=JSON.stringify(route.request().postDataJSON());const key=request.match(/asu_[A-Za-z0-9_-]{8,64}/)?.[0];expect(key).toBeTruthy()
  const facts=[{stableKey:'fact.arrival',kind:'event',statement:'林岚到达车站。',subjectKeys:[],sourceUnitKeys:[key],confidence:1},{stableKey:'fact.wait',kind:'event',statement:'她决定等待。',subjectKeys:[],sourceUnitKeys:[key],confidence:1}]
  await route.fulfill({contentType:'application/json',body:JSON.stringify({choices:[{message:{role:'assistant',content:JSON.stringify(facts)},finish_reason:'stop'}],usage:{prompt_tokens:100,completion_tokens:100,total_tokens:200}})})
 })
 await page.goto('./script/library?create=1')
 await page.getByLabel('剧本名称',{exact:true}).fill('候选恢复剧本')
 await page.getByLabel('来源方式',{exact:true}).selectOption('import')
 await page.getByLabel('导入原作内容').fill('林岚走进车站。她决定等待。')
 await page.getByRole('button',{name:'冻结来源并创建剧本',exact:true}).click()
 await expect(page).toHaveURL(/source\?work=\d+/)
 await page.getByRole('button',{name:/1 来源事实/}).click()
 const candidate=page.locator('.screenplay-professional-candidate')
 await expect(candidate).toBeVisible()
 await candidate.locator('.screenplay-candidate-items input').nth(1).uncheck()
 await candidate.getByLabel('第1项 原作事实',{exact:true}).fill('作者核对：林岚到达旧车站。')
 await expect(candidate.locator('.screenplay-candidate-items input').nth(1)).not.toBeChecked()
 await page.getByRole('navigation',{name:'剧本页面导航'}).getByRole('button',{name:'改编目标',exact:true}).click()
 await expect(page).toHaveURL(/script\/brief\?work=\d+/)
 await page.reload()
 await expect(candidate.getByLabel('第1项 原作事实',{exact:true})).toHaveValue('作者核对：林岚到达旧车站。')
 await expect(candidate.locator('.screenplay-candidate-items input').nth(1)).not.toBeChecked()
 expect(calls).toBe(1)
 await candidate.getByRole('button',{name:'作者确认并采纳',exact:true}).click()
 await expect(candidate).toHaveCount(0)
 await page.getByRole('navigation',{name:'剧本页面导航'}).getByRole('button',{name:'原作与来源',exact:true}).click()
 await page.getByRole('navigation',{name:'页面内导航'}).getByRole('button',{name:'原作事实',exact:true}).click()
 await expect(page.getByLabel('第1项 原作事实',{exact:true})).toHaveValue('作者核对：林岚到达旧车站。')
 await expect(page.getByLabel('第2项 原作事实',{exact:true})).toHaveCount(0)
})

for (const profile of ['long','short'] as const) test(`adapting a ${profile} novel preserves its library, edits and other product ownership`,async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('storyforge_guide_completed','e2e'))
 await page.goto('./script/library')
 // Only the source manuscript is seeded; selection, adaptation and library operations use the UI.
 const source=await page.evaluate(async profile=>{
  const importer=new Function('path','return import(path)') as (path:string)=>Promise<any>
  const {createWorkspace}=await importer('/storyforge/src/lib/workspace/create-workspace.ts')
  const text='林岚赶到车站，决定留下等待弟弟。'
  return (await createWorkspace({name:'原作保留验收',description:'独立原作',genres:[],status:'drafting',targetWordCount:profile==='short'?5000:100000},{purpose:'independent-work',kind:'novel',novelProfile:profile,...(profile==='short'?{preferredChapterCount:3,initialChapterContent:text}:{importedNovelText:text})})).scope
 },profile)
 await page.getByRole('button',{name:'新建剧本改编',exact:true}).click()
 await page.getByLabel('小说来源').selectOption({label:'原作保留验收'})
 await page.getByLabel('剧本名称',{exact:true}).fill('保留独立剧本')
 await page.getByRole('button',{name:'冻结来源并创建剧本',exact:true}).click()
 await expect(page).toHaveURL(/script\/source\?work=\d+/)
 const scriptUrl=page.url()
 await page.goto(`./${profile}${profile==='short'?'/library':''}`)
 let book=page.locator('article').filter({has:page.getByRole('heading',{name:'原作保留验收',exact:true})})
 await expect(book).toBeVisible()
 await book.getByRole('button',{name:'重命名',exact:true}).click()
 await page.getByRole('dialog').getByRole('textbox').fill('修改后的原作')
 await page.getByRole('dialog').getByRole('button',{name:'保存名称',exact:true}).click()
 book=page.locator('article').filter({has:page.getByRole('heading',{name:'修改后的原作',exact:true})})
 await expect(book).toBeVisible()
 await book.getByRole('button',{name:profile==='long'?'进入长篇工作台':'继续创作',exact:true}).click()
 await expect(page).toHaveURL(profile==='long'?/workspace\/\d+\?module=info/:/short\/intent\?project=\d+/)
 await expect.poll(()=>page.evaluate(async id=>{
  const importer=new Function('path','return import(path)') as (path:string)=>Promise<any>
  const {db}=await importer('/storyforge/src/lib/db/schema.ts');return (await db.projects.get(id))?.activeWorkId
 },source.projectId)).toBe(source.workId)
 await page.goto('./script/library')
 await expect(page.locator('article').getByRole('heading',{name:'保留独立剧本',exact:true})).toBeVisible()
 await page.goto(scriptUrl)
 await expect(page.getByRole('navigation',{name:'剧本页面导航'})).toBeVisible()
 await page.goto(`./${profile}${profile==='short'?'/library':''}`)
 await page.locator('article').filter({has:page.getByRole('heading',{name:'修改后的原作',exact:true})}).getByRole('button',{name:'删除作品',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'继续',exact:true}).click()
 const download=page.waitForEvent('download')
 await page.getByRole('dialog').getByRole('button',{name:'立即备份',exact:true}).click()
 expect((await download).suggestedFilename()).toMatch(/\.json$/)
 await expect(page.locator('article').getByRole('heading',{name:'修改后的原作',exact:true})).toHaveCount(0)
 await page.goto('./script/library')
 await expect(page.locator('article').getByRole('heading',{name:'保留独立剧本',exact:true})).toBeVisible()
})
