import type { AiTownAuthoringSettingsV1 } from '../../lib/ai-town/authoring-contract';

export default function AuthorSettings({settings,onChange,page}:{settings:AiTownAuthoringSettingsV1;onChange:(s:AiTownAuthoringSettingsV1)=>void;page:string}){
 const t=settings.town;
 const set=<K extends keyof AiTownAuthoringSettingsV1['town']>(key:K,value:AiTownAuthoringSettingsV1['town'][K])=>onChange({...settings,town:{...t,[key]:value}});
 const text=(key:'playerName'|'homeConcept'|'sharedProjectConcept',label:string)=><label key={key}>{label}<textarea value={t[key]} maxLength={1000} onChange={e=>set(key,e.target.value)}/></label>;
 const num=(key:'elapsedDays'|'residentTarget'|'majorLocationTarget'|'actionsPerDay'|'offlineMaximumDays'|'startingMoney',label:string,min:number,max:number)=><label key={key}>{label}<input type="number" min={min} max={max} value={t[key]} onChange={e=>set(key,Number(e.target.value))}/></label>;
 const toggle=(key:'offlineEnabled'|'portraits'|'expressions'|'locationCards'|'ambientAudio',label:string)=><label className="town-check" key={key}><input type="checkbox" checked={t[key]} onChange={e=>set(key,e.target.checked)}/>{label}</label>;
 return <div className="avg-form town-settings">
 {page==='vision'&&<><label>玩家身份<select value={t.playerRole} onChange={e=>set('playerRole',e.target.value as typeof t.playerRole)}><option value="new-resident">新居民</option><option value="caretaker">共同体照料者</option></select></label>{text('playerName','玩家称呼')}{text('homeConcept','住所构想')}{num('elapsedDays','世界结局后经过的天数',1,36500)}<label>生活愿景与开场目标<textarea value={settings.openingSituation} maxLength={2000} onChange={e=>onChange({...settings,openingSituation:e.target.value})}/></label></>}
 {page==='residents'&&<>{num('residentTarget','居民数量（须与所选世界居民一致）',4,8)}{num('majorLocationTarget','主要地点数量',4,12)}{text('sharedProjectConcept','共同建设目标')}<p>在世界引擎页选择结局、居民及地点来源。居民档案和具体日程会在制作后供你检查。</p></>}
 {page==='rhythm'&&<>{num('actionsPerDay','每天可用行动次数',1,6)}{num('startingMoney','初始货币',0,100000)}<fieldset><legend>资源种类（1～3 类）</legend>{[...new Set(['materials','food','care',...t.resourceKeys])].map(key=><label className="town-check" key={key}><input type="checkbox" checked={t.resourceKeys.includes(key)} disabled={!t.resourceKeys.includes(key)&&t.resourceKeys.length>=3} onChange={e=>set('resourceKeys',e.target.checked?[...t.resourceKeys,key]:t.resourceKeys.filter(v=>v!==key))}/>{{materials:'材料',food:'食物',care:'照料'}[key]??key}</label>)}</fieldset><label>恋爱边界<select value={t.romance} onChange={e=>set('romance',e.target.value as typeof t.romance)}><option value="off">关闭</option><option value="canon-only">仅保留世界已有关系</option><option value="opt-in">明确同意后发展</option></select></label>{toggle('offlineEnabled','启用有限离线推进')}{num('offlineMaximumDays','每次离线推进上限（天）',1,3)}<p>每天六个时段。死亡、永久离开、婚育、重大设施及世界规则变化需要你确认；居民的私密心智不会公开。</p></>}
 {page==='media-plan'&&<>{toggle('portraits','居民立绘')}{toggle('expressions','表情变化')}{toggle('locationCards','地点画面')}{toggle('ambientAudio','环境音')}<label>制作质量<select value={settings.qualityProfile} onChange={e=>onChange({...settings,qualityProfile:e.target.value as typeof settings.qualityProfile})}><option value="prototype">原型（占位素材）</option><option value="internal">内部评审</option><option value="commercial-candidate">商业候选（须验收）</option></select></label><p>原型可使用明确标注的占位素材；正式图片、音频需要已配置的服务与使用权。缺失素材会显示原因。</p></>}
 {page==='confirm'&&<><p>生活目标：{settings.openingSituation||'尚未填写'}</p><p>{t.residentTarget} 位居民 · {t.majorLocationTarget} 个地点 · 每日 {t.actionsPerDay} 次行动</p><p>共同目标：{t.sharedProjectConcept}</p><p>离线推进：{t.offlineEnabled?`最多 ${t.offlineMaximumDays} 天`:'关闭'}。生成审查方案只保存配置；到制作流程再次明确授权后才开始生产。</p></>}
 </div>
}
