/** Human-readable fields for the existing closed comic contracts. */
const labels: Record<string,string> = {
 chapterNumber:'所属章',pageNumber:'页码',narrativeFunction:'叙事功能',visualAction:'视觉动作',dialogueIntent:'对白意图',emotion:'情绪',estimatedPanels:'预计格数',goal:'本页目标',beatKeys:'关联节拍',endReveal:'页末揭示',pageTurn:'翻页效果',expectedPanelCount:'预计格数',textBudget:'文字预算',global:'全局画风',subjects:'视觉主体',label:'名称',design:'外观设计',artDirection:'美术方向',linework:'线条',palette:'色板',lighting:'光线',periodAndMaterials:'时代与材质',cameraLanguage:'镜头语言',prohibitedDepictions:'禁止描绘',negativeConstraints:'禁止项',description:'设计描述',silhouette:'轮廓',facialFeatures:'面部特征',hairAndCostume:'发型与服装',materials:'材质',distinguishingMarks:'识别特征',prohibitedChanges:'禁止变化',costume:'服装',condition:'当前状态',props:'道具',position:'位置',subjectKey:'视觉主体',note:'连续性说明',moment:'画面瞬间',pagePlanKey:'所属分页',nextPanelKey:'下一格',frame:'位置与尺寸',x:'横向位置',y:'纵向位置',width:'宽度',height:'高度',shot:'镜头',size:'景别',angle:'角度',movement:'运动',composition:'构图',subjectStates:'本格主体状态',continuityRefs:'连续性关联',protectedAreas:'文字保留区',lettering:'排字',visualPrompt:'画面要求',negativePrompt:'负向要求',referenceSubjectKeys:'参考主体',
intExt:'内外景',location:'地点',timeOfDay:'时段',
  coreTheme:'核心主题',dominantEmotion:'主导情绪',mustKeep:'必须保留',mayCut:'允许删去',mayMerge:'允许合并',mayReorder:'允许重排',allowedAdditions:'允许新增',audience:'目标观众',rating:'内容分级',targetScale:'目标规模',narrativePerspective:'叙事视角',timeBudget:'时长安排',costLimit:'制作限制',deviationNotes:'改编边界',unresolvedQuestions:'待确认问题',assumptions:'新增假设',
  statement:'原作事实',kind:'事实类型',subjectKeys:'涉及人物或事物',sourceUnitKeys:'原作依据',confidence:'确信程度',fromFactKey:'起因事实',toFactKey:'结果事实',relation:'因果关系',rationale:'取舍理由',action:'改编方式',sourceFactKeys:'关联事实',targetKeys:'改编目标标识',
  sectionKey:'结构段标识',sectionTitle:'幕或段落名称',scope:'结构层级',episodeNumber:'集数',sceneNumber:'场次编号',order:'排列顺序',objective:'叙事目标',conflict:'冲突与阻力',turn:'转折',outcome:'结果',causalFactKeys:'因果事实',decisionKeys:'改编决定',estimatedSeconds:'预计秒数',beatKey:'所属节拍',purpose:'场次目的',entryState:'入场状态',exitState:'离场状态',visibleAction:'可见行动',informationReveal:'信息揭示',
  category:'审查类型',severity:'严重程度',sceneKey:'目标场次',blockId:'目标段落',evidence:'原文证据',problem:'问题',suggestion:'建议',summary:'场次概述',blocks:'剧本段落',text:'内容',name:'角色名称',type:'段落类型',extension:'对白扩展',dualDialogue:'双栏对白',
  format:'剧本类型',language:'语言',episodeCount:'总集数',targetMinutesPerEpisode:'单集目标分钟',dialogueDensity:'对白密度',productionScale:'制作规模',preserveVoiceOver:'保留旁白',titlePage:'标题页',creditLine:'署名说明',authorDisplayName:'作者署名',contactText:'联系方式',copyrightNotice:'版权说明',draftLabel:'稿件名称',exportDefaults:'默认导出格式',
}
const choices: Record<string,string[]>={narrativeFunction:['establish','develop','reveal','reaction','turn','climax','resolution','transition'],pageTurn:['none','setup','reveal-after-turn','cliffhanger'],format:['film','series','short-drama'],scope:['act','sequence','episode'],dialogueDensity:['low','balanced','high'],productionScale:['contained','standard','large'],action:['keep','cut','merge','reorder','externalize','add'],relation:['cause','enables','prevents','motivates','reveals'],kind:['event','character-state','relationship','location','object','motif'],severity:['critical','major','minor'],type:['action','character','parenthetical','dialogue','transition','shot','note']}
const names: Record<string,string>={establish:'建立',develop:'推进',reveal:'揭示',reaction:'反应',turn:'转折',climax:'高潮',resolution:'收束',transition:'过渡',none:'无',setup:'铺垫','reveal-after-turn':'翻页后揭示',question:'悬问',cliffhanger:'悬念',breath:'留白',location:'地点',object:'物件',motif:'意象',film:'电影',series:'剧集','short-drama':'短剧',act:'幕',sequence:'段落',episode:'集',low:'精简',balanced:'均衡',high:'密集',contained:'小规模',standard:'标准',large:'大规模',keep:'保留',cut:'删去',merge:'合并',reorder:'重排',externalize:'外化',add:'新增',cause:'导致',enables:'促成',prevents:'阻止',motivates:'驱动',reveals:'揭示',event:'事件','character-state':'人物状态',relationship:'关系',setting:'环境',constraint:'约束',theme:'主题',critical:'阻塞',major:'重要',minor:'一般'}
export type FieldOption = {value:string;label:string}
export default function ComicFields({value,onChange,options={},prefix=''}:{value:unknown;onChange:(v:any)=>void;options?:Record<string,FieldOption[]>;prefix?:string}) {
  if(Array.isArray(value)&&value.some(item=>item&&typeof item==='object'))return <div className="cp-records">{value.map((item,i)=><section className="cp-record" key={i}><h4>第 {i+1} 项</h4><ComicFields value={item} options={options} prefix={`${prefix}第${i+1}项 `} onChange={next=>onChange(value.map((v,j)=>i===j?next:v))}/><button type="button" onClick={()=>onChange(value.filter((_,j)=>i!==j))}>移除此项</button></section>)}</div>
  if(!value||typeof value!=='object'||Array.isArray(value))return null
  return <div className="cp-fields">{Object.entries(value).filter(([key])=>!['version','stableKey','id','expectedPanelRevision'].includes(key)).map(([key,v])=>{
    const kindOptions=key==='kind'&&'design' in value?[['character','人物'],['location','地点'],['prop','道具'],['style','风格']]:key==='kind'&&'fontFamily' in value?[['speech','对白'],['thought','内心'],['caption','旁白'],['sfx','拟声']]:null
    const label=kindOptions?('design' in value?'主体类型':'排字类型'):key==='kind'&&options.kind?'主体类型':labels[key]??key;const opts=kindOptions?.map(([value,label])=>({value,label}))??options[key]??choices[key]?.map(value=>({value,label:names[value]??value}));const change=(next:unknown)=>onChange({...value,[key]:next})
    if(v&&typeof v==='object'&&!Array.isArray(v))return <section className="cp-wide" key={key}><h4>{label}</h4><ComicFields value={v} onChange={change} options={options} prefix={prefix+label+' '}/></section>
    if(Array.isArray(v)&&!v.length&&['subjects','subjectStates','lettering','protectedAreas'].includes(key))return <p className="cp-wide" key={key}>{label}：尚无条目，可使用下方添加按钮。</p>
    if(Array.isArray(v)&&v.some(item=>item&&typeof item==='object'))return <section className="cp-wide" key={key}><h4>{label}</h4><ComicFields value={v} onChange={change} options={options} prefix={prefix+'段落 '}/></section>
    return <label className={Array.isArray(v)||typeof v==='string'&&!opts?'cp-wide':''} key={key}><span>{label}</span>{typeof v==='boolean'?<input aria-label={prefix+label} type="checkbox" checked={v} onChange={e=>change(e.target.checked)}/>:opts?Array.isArray(v)?<select multiple aria-label={prefix+label} value={v as string[]} onChange={e=>change(Array.from(e.target.selectedOptions,o=>o.value))}>{opts.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<select aria-label={prefix+label} value={String(v??'')} onChange={e=>change(e.target.value)}>{!opts.some(o=>o.value===v)&&<option value={String(v??'')}>{String(v??'请选择')}</option>}{opts.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:Array.isArray(v)?<textarea aria-label={prefix+label} rows={2} value={v.join('\n')} onChange={e=>change(e.target.value.split('\n'))} onBlur={()=>change(v.filter(x=>String(x).trim()))}/>:typeof v==='number'?<input aria-label={prefix+label} type="number" value={v} onChange={e=>change(Number(e.target.value))}/>:<textarea aria-label={prefix+label} rows={2} value={String(v??'')} onChange={e=>change(e.target.value)}/>}</label>
  })}</div>
}
