import {useEffect,useState} from 'react'
import type {CreationReleaseV1,WorkspaceScope} from '../../lib/types'
import {listComicReleasesV1} from '../../lib/comic/release'
import {readComicReleaseBookV1} from '../../lib/comic/release-book'
import {renderComicArchiveV1,renderComicPageSvgV1,renderComicPrintHtmlV1,renderComicStoryboardTextV1} from '../../lib/comic/renderers'
export default function ComicReleaseHistory({scope,revision}:{scope:WorkspaceScope;revision:number}) {
 const [releases,setReleases]=useState<CreationReleaseV1[]>([]),[selected,setSelected]=useState<Awaited<ReturnType<typeof readComicReleaseBookV1>>|null>(null),[selectedId,setSelectedId]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{void listComicReleasesV1(scope).then(setReleases).catch(c=>setError(String(c)))},[scope,revision])
 const download=(name:string,data:Blob)=>{const url=URL.createObjectURL(data);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
 const open=async(id:number)=>{setBusy(true);setError('');try{setSelected(await readComicReleaseBookV1(scope,id));setSelectedId(id)}catch(c){setError(String(c))}finally{setBusy(false)}}
 const archive=async(format:'png-zip'|'webp-zip'|'cbz')=>{if(!selected)return;setBusy(true);setError('');try{download(`${selected.manifest.work.title}-版本${releases.find(r=>r.id===selectedId)?.version}.${format==='cbz'?'cbz':'zip'}`,await renderComicArchiveV1({...selected.book,format,mode:selected.mode}))}catch(c){setError(String(c))}finally{setBusy(false)}}
 const print=async()=>{if(!selected)return;const win=window.open('','_blank');if(!win)return setError('请允许打开打印窗口');setBusy(true);try{win.document.write(await renderComicPrintHtmlV1({...selected.book,mode:selected.mode}));win.document.close();win.focus();win.print()}catch(c){win.close();setError(String(c))}finally{setBusy(false)}}
 return <section className="cp-planning cp-release-history"><h3>发布版本</h3><p>查看或导出当时确认的内容。继续修改作品不会改变这些版本。</p>{error&&<p role="alert">{error}</p>}{!releases.length&&<p>尚无发布版本。完成审校后，可在本页下方发布分镜版或视觉成品版。</p>}<div className="comic-release-list">{releases.map(r=><article key={r.id}><strong>v{r.version} · {r.label}</strong><small>{new Date(r.createdAt).toLocaleString()}</small><button disabled={busy} onClick={()=>void open(r.id!)}>查看版本 v{r.version}</button></article>)}</div>{selected&&<><h4>版本 v{releases.find(r=>r.id===selectedId)?.version} · {selected.manifest.tier==='visual'?'视觉成品':'分镜资料'}</h4><div className="comic-export-grid"><button disabled={busy} onClick={()=>download('漫画发布版本.json',new Blob([JSON.stringify(selected.manifest,null,2)],{type:'application/json'}))}>导出此版本 JSON</button><button disabled={busy} onClick={()=>download('漫画发布版本.md',new Blob([renderComicStoryboardTextV1(selected.book)],{type:'text/markdown'}))}>导出此版本脚本</button>{(['png-zip','webp-zip','cbz'] as const).map(f=><button disabled={busy} key={f} onClick={()=>void archive(f)}>导出此版本 {f.toUpperCase()}</button>)}<button disabled={busy} onClick={()=>void print()}>打印此版本 PDF</button></div><div className="cp-reader">{selected.book.pages.map(p=><div key={p.page.stableKey} dangerouslySetInnerHTML={{__html:renderComicPageSvgV1({...p,targetSpec:selected.book.targetSpec,mode:selected.mode})}}/>)}</div></>}</section>
}
