import type { ShortNovelArtifactKindV1 } from '../../lib/short-novel/prompts'

type Field = [string, string, 'text' | 'area' | 'list' | 'number' | 'pov' | 'tense']
const brief: Field[] = [['premise','故事前提','area'],['coreChange','核心变化','area'],['dominantEmotion','主导情绪','text'],['pointOfView','叙事视角','pov'],['tense','叙事时态','tense'],['audience','目标读者','text'],['storyPromise','阅读承诺','area'],['mustKeep','必须保留（每行一项）','list'],['forbidden','避免内容（每行一项）','list'],['targetWordCount','目标字数','number'],['chapterCount','章节数量','number']]
const design: Field[] = [['protagonist','主人公','area'],['desire','主人公的欲望','area'],['pressure','开场压力','area'],['escalation','逐次升级（每行一项）','list'],['irreversibleTurn','不可逆转折','area'],['climaxChoice','高潮选择','area'],['endingImage','结尾画面','area'],['aftertaste','余韵','area'],['thematicQuestion','主题问题','area']]
const plan: Field[] = [['title','章节标题','text'],['purpose','叙事目标','area'],['viewpoint','本章视角','text'],['openingPressure','开场压力','area'],['conflict','本章冲突','area'],['turn','本章转折','area'],['exitState','离场状态','area'],['targetWordCount','字数预算','number']]
function Fields({ fields, value, change, prefix = '' }: { fields: Field[]; value: Record<string, unknown>; change: (value: Record<string, unknown>) => void; prefix?: string }) {
  return <div className="short-fields">{fields.map(([key,label,type]) => <label key={key} className={['area','list'].includes(type) ? 'wide' : ''}><span>{label}</span>{type === 'pov' || type === 'tense' ? <select aria-label={prefix+label} value={String(value[key] ?? '')} onChange={event => change({...value,[key]:event.target.value})}>{(type === 'pov' ? [['first-person','第一人称'],['third-limited','第三人称限知'],['third-omniscient','第三人称全知']] : [['past','过去时'],['present','现在时']]).map(([id,text]) => <option key={id} value={id}>{text}</option>)}</select> : type === 'area' || type === 'list' ? <textarea aria-label={prefix+label} rows={3} value={type === 'list' ? (Array.isArray(value[key]) ? (value[key] as string[]).join('\n') : '') : String(value[key] ?? '')} onChange={event => change({...value,[key]:type === 'list' ? event.target.value.split('\n') : event.target.value})} onBlur={() => { if(type === 'list') change({...value,[key]:(value[key] as string[] ?? []).map(item=>item.trim()).filter(Boolean)}) }}/> : <input aria-label={prefix+label} type={type === 'number' ? 'number' : 'text'} value={String(value[key] ?? '')} onChange={event => change({...value,[key]:type === 'number' ? Number(event.target.value) : event.target.value})}/>}</label>)}</div>
}

export default function ShortNovelFields({ kind, text, onChange }: { kind: ShortNovelArtifactKindV1; text: string; onChange: (text:string)=>void }) {
  let value: any
  try { value = JSON.parse(text) } catch { return <label>内容格式需要修正<textarea aria-label="修正候选格式" value={text} onChange={event=>onChange(event.target.value)}/></label> }
  if (!value || typeof value !== 'object') return <p role="alert">内容格式不正确，请重新生成。</p>
  if ((kind === 'scene-plan' && (!Array.isArray(value) || value.some((item:unknown)=>!item || typeof item !== 'object'))) || (kind === 'continuity-review' && (!Array.isArray(value.issues) || value.issues.some((item:unknown)=>!item || typeof item !== 'object')))) return <label>内容格式需要修正<textarea aria-label="修正候选格式" value={text} onChange={event=>onChange(event.target.value)}/></label>
  const change = (next: unknown) => onChange(JSON.stringify(next, null, 2))
  if (kind === 'brief' || kind === 'story-design') return <Fields fields={kind === 'brief' ? brief : design} value={value} change={change}/>
  if (kind === 'scene-plan') return Array.isArray(value) ? <div className="short-card-list">{value.map((card,index)=><section className="short-chapter-card" key={card.stableKey ?? index}><h4>第 {index+1} 章</h4><Fields fields={plan} value={card} prefix={`第${index+1}章 `} change={next=>change(value.map((item:any,i:number)=>i===index?next:item))}/></section>)}</div> : <p role="alert">章节卡应为有序列表。</p>
  if (kind === 'chapter-draft' || kind === 'targeted-rewrite') return <><p>目标：{value.chapterKey} · {kind === 'targeted-rewrite' ? '修改范围为本章全文，请逐段检查后采纳。' : '仅写入此章。'}</p><Fields fields={[['title','候选章节标题','text'],['content','候选正文','area']]} value={value} change={change}/></>
  return <><Fields fields={[['summary','审校结论','area'],['strengths','优点（每行一项）','list']]} value={value} change={change}/><div className="short-card-list">{(value.issues ?? []).map((issue:any,index:number)=><section className="short-chapter-card" key={issue.stableKey}><h4>问题 {index+1}</h4><label>严重程度<select aria-label={`问题${index+1} 严重程度`} value={issue.severity} onChange={event=>change({...value,issues:value.issues.map((item:any,i:number)=>i===index?{...item,severity:event.target.value}:item)})}>{[['critical','阻塞'],['major','重要'],['minor','一般']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><Fields fields={[['chapterKeys','关联章节（每行一个，如 chapter-1）','list'],['evidence','原文证据（含带引号的短引文）','area'],['problem','问题描述','area'],['suggestion','修改建议','area']]} value={issue} prefix={`问题${index+1} `} change={next=>change({...value,issues:value.issues.map((item:any,i:number)=>i===index?next:item)})}/><button onClick={()=>change({...value,issues:value.issues.filter((_:unknown,i:number)=>i!==index)})}>移除此问题</button></section>)}</div><button onClick={()=>change({...value,issues:[...(value.issues??[]),{stableKey:crypto.randomUUID(),severity:'major',category:'continuity',chapterKeys:['chapter-1'],evidence:'',problem:'',suggestion:'',status:'open'}]})}>添加审校问题</button></>
}
